declare module "com.aetherteam.aether.api.registers.AdvancementSoundOverride" {
import {$Predicate, $Predicate$$Type} from "java.util.function.Predicate"
import {$Supplier, $Supplier$$Type} from "java.util.function.Supplier"
import {$SoundEvent, $SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"
import {$AdvancementHolder, $AdvancementHolder$$Type} from "net.minecraft.advancements.AdvancementHolder"
import {$Record} from "java.lang.Record"

export class $AdvancementSoundOverride extends $Record {
constructor(priority: integer, predicate: $Predicate$$Type<($AdvancementHolder)>, sound: $Supplier$$Type<($SoundEvent$$Type)>)

public "priority"(): integer
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "matches"(arg0: $AdvancementHolder$$Type): boolean
public "predicate"(): $Predicate<($AdvancementHolder)>
public "sound"(): $Supplier<($SoundEvent)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.AetherAdvancementSoundOverride
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.AetherAdvancementSoundOverrideTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AdvancementSoundOverride$$Type = (Special.AetherAdvancementSoundOverride) | ({"sound"?: $Supplier$$Type<($SoundEvent$$Type)>, "priority"?: integer, "predicate"?: $Predicate$$Type<($AdvancementHolder$$Type)>}) | ([sound?: $Supplier$$Type<($SoundEvent$$Type)>, priority?: integer, predicate?: $Predicate$$Type<($AdvancementHolder$$Type)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AdvancementSoundOverride$$Original = $AdvancementSoundOverride;}
declare module "com.aetherteam.aether.api.registers.MoaType" {
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$Record} from "java.lang.Record"

export class $MoaType extends $Record {
static readonly "CODEC": $Codec<($MoaType)>

constructor(egg: $ItemStack$$Type, maxJumps: integer, speed: float, spawnChance: integer, moaTexture: $ResourceLocation$$Type, saddleTexture: $ResourceLocation$$Type, jumpsTexture: ($ResourceLocation$$Type)?)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "jumpsTexture"(): $Optional<($ResourceLocation)>
public "egg"(): $ItemStack
public "saddleTexture"(): $ResourceLocation
public "speed"(): float
public "spawnChance"(): integer
public "moaTexture"(): $ResourceLocation
public "maxJumps"(): integer
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.AetherMoaType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.AetherMoaTypeTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MoaType$$Type = (Special.AetherMoaType) | ({"maxJumps"?: integer, "moaTexture"?: $ResourceLocation$$Type, "spawnChance"?: integer, "egg"?: $ItemStack$$Type, "saddleTexture"?: $ResourceLocation$$Type, "speed"?: float, "jumpsTexture"?: ($ResourceLocation$$Type)?}) | ([maxJumps?: integer, moaTexture?: $ResourceLocation$$Type, spawnChance?: integer, egg?: $ItemStack$$Type, saddleTexture?: $ResourceLocation$$Type, speed?: float, jumpsTexture?: ($ResourceLocation$$Type)?]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MoaType$$Original = $MoaType;}
