declare module "dev.shadowsoffire.apothic_spawners.stats.VanillaStat" {
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$MutableComponent, $MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$Component} from "net.minecraft.network.chat.Component"
import {$SpawnerStat$$Type, $SpawnerStat$$Interface} from "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat"

export class $VanillaStat implements $SpawnerStat$$Interface<(integer)> {
public "name"(): $MutableComponent
public "getValue"(arg0: $ApothSpawnerTile$$Type): integer
public "getId"(): $ResourceLocation
public "setValue"(arg0: $ApothSpawnerTile$$Type, arg1: integer): void
public "desc"(): $MutableComponent
public "formatValue"(arg0: integer): StringJS
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
public "getTooltip"(arg0: $ApothSpawnerTile$$Type): $Component
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: integer, arg2: (integer)?, arg3: (integer)?): boolean
public "getValueCodec"(): $Codec<(integer)>
get "id"(): $ResourceLocation
get "valueCodec"(): $Codec<(integer)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VanillaStat$$Type = ($VanillaStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VanillaStat$$Original = $VanillaStat;}
declare module "dev.shadowsoffire.apothic_spawners.stats.CustomStat" {
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MutableComponent, $MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$Component} from "net.minecraft.network.chat.Component"
import {$SpawnerStat$$Type, $SpawnerStat$$Interface} from "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat"

export class $CustomStat<T> implements $SpawnerStat$$Interface<(T)> {
constructor(arg0: T)

public "toString"(): StringJS
public "getValue"(arg0: $ApothSpawnerTile$$Type): T
public "setValue"(arg0: $ApothSpawnerTile$$Type, arg1: T): void
public "getTooltip"(arg0: $ApothSpawnerTile$$Type): $Component
public "getTooltipImpl"(arg0: $ApothSpawnerTile$$Type): $Component
public "name"(): $MutableComponent
public "getId"(): $ResourceLocation
public "desc"(): $MutableComponent
public "formatValue"(arg0: T): StringJS
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: T, arg2: (T)?, arg3: (T)?): boolean
public "getValueCodec"(): $Codec<(T)>
get "id"(): $ResourceLocation
get "valueCodec"(): $Codec<(T)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomStat$$Type<T> = ($CustomStat<(T)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomStat$$Original<T> = $CustomStat<(T)>;}
declare module "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat" {
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$MutableComponent, $MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$Component} from "net.minecraft.network.chat.Component"

export interface $SpawnerStat$$Interface<T> {
get "id"(): $ResourceLocation
get "valueCodec"(): $Codec<(T)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.ApothicSpawnersSpawnerStat
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.ApothicSpawnersSpawnerStatTag
}

export class $SpawnerStat<T> implements $SpawnerStat$$Interface {
 "name"(): $MutableComponent
 "getValue"(arg0: $ApothSpawnerTile$$Type): T
 "getId"(): $ResourceLocation
 "setValue"(arg0: $ApothSpawnerTile$$Type, arg1: T): void
 "desc"(): $MutableComponent
 "formatValue"(arg0: T): StringJS
static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
 "getTooltip"(arg0: $ApothSpawnerTile$$Type): $Component
 "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: T, arg2: (T)?, arg3: (T)?): boolean
 "getValueCodec"(): $Codec<(T)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SpawnerStat$$Type<T> = (Special.ApothicSpawnersSpawnerStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SpawnerStat$$Original<T> = $SpawnerStat<(T)>;}
declare module "dev.shadowsoffire.apothic_spawners.stats.PercentageStat" {
import {$CustomStat} from "dev.shadowsoffire.apothic_spawners.stats.CustomStat"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$Component} from "net.minecraft.network.chat.Component"
import {$SpawnerStat$$Type} from "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat"

export class $PercentageStat extends $CustomStat<(float)> {
constructor(arg0: float)

public "formatValue"(arg0: any): StringJS
public "formatValue"(arg0: float): StringJS
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: any, arg2: $Optional$$Type, arg3: $Optional$$Type): boolean
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: float, arg2: (float)?, arg3: (float)?): boolean
public "getTooltipImpl"(arg0: $ApothSpawnerTile$$Type): $Component
public "getValueCodec"(): $Codec<(float)>
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
get "valueCodec"(): $Codec<(float)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $PercentageStat$$Type = ($PercentageStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $PercentageStat$$Original = $PercentageStat;}
declare module "dev.shadowsoffire.apothic_spawners.stats.LevelStat" {
import {$CustomStat} from "dev.shadowsoffire.apothic_spawners.stats.CustomStat"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$Component} from "net.minecraft.network.chat.Component"
import {$SpawnerStat$$Type} from "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat"

export class $LevelStat extends $CustomStat<(integer)> {
constructor(arg0: integer)

public "formatValue"(arg0: integer): StringJS
public "formatValue"(arg0: any): StringJS
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: any, arg2: $Optional$$Type, arg3: $Optional$$Type): boolean
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: integer, arg2: (integer)?, arg3: (integer)?): boolean
public "getTooltipImpl"(arg0: $ApothSpawnerTile$$Type): $Component
public "getValueCodec"(): $Codec<(integer)>
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
get "valueCodec"(): $Codec<(integer)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $LevelStat$$Type = ($LevelStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $LevelStat$$Original = $LevelStat;}
declare module "dev.shadowsoffire.apothic_spawners.stats.BooleanStat" {
import {$CustomStat} from "dev.shadowsoffire.apothic_spawners.stats.CustomStat"
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MutableComponent$$Type} from "net.minecraft.network.chat.MutableComponent"
import {$ApothSpawnerTile$$Type} from "dev.shadowsoffire.apothic_spawners.block.ApothSpawnerTile"
import {$Component} from "net.minecraft.network.chat.Component"
import {$SpawnerStat$$Type} from "dev.shadowsoffire.apothic_spawners.stats.SpawnerStat"

export class $BooleanStat extends $CustomStat<(boolean)> {
constructor(arg0: boolean)

public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: boolean, arg2: (boolean)?, arg3: (boolean)?): boolean
public "applyModifier"(arg0: $ApothSpawnerTile$$Type, arg1: any, arg2: $Optional$$Type, arg3: $Optional$$Type): boolean
public "getTooltipImpl"(arg0: $ApothSpawnerTile$$Type): $Component
public "getValueCodec"(): $Codec<(boolean)>
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: $MutableComponent$$Type): $Component
public static "createTooltip"(arg0: $SpawnerStat$$Type<(never)>, arg1: StringJS): $Component
get "valueCodec"(): $Codec<(boolean)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BooleanStat$$Type = ($BooleanStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BooleanStat$$Original = $BooleanStat;}
