declare module "moe.wolfgirl.probejs.generated.registry.irons_spellbooks.Spells" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CustomSpell$Builder} from "com.squoshi.irons_spells_js.spell.CustomSpell$Builder"
import {$AbstractSpell} from "io.redspace.ironsspellbooks.api.spells.AbstractSpell"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Spells extends $RegistryKubeEvent<($AbstractSpell)> {
public "create"(name: StringJS): $CustomSpell$Builder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Spells$$Type = ($Spells);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Spells$$Original = $Spells;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Blasting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Blasting$$Type = ($Blasting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Blasting$$Original = $Blasting;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.SpiritFocusing" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$SpiritIngredient$$Type} from "com.sammy.malum.core.systems.recipe.SpiritIngredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SpiritFocusing extends $KubeRecipe {
public "input"(input: $Ingredient$$Type): this
public "result"(result: $ItemStack$$Type): this
public "spirits"(spirits: $List$$Type<($SpiritIngredient$$Type)>): this
public "time"(time: integer): this
public "durabilityCost"(durabilityCost: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SpiritFocusing$$Type = ($SpiritFocusing);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SpiritFocusing$$Original = $SpiritFocusing;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShapeless$$Type = ($CraftingShapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShapeless$$Original = $CraftingShapeless;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CreativeModeTab" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CreativeModeTab as $CreativeModeTab$0} from "net.minecraft.world.item.CreativeModeTab"
import {$CreativeTabBuilder} from "dev.latvian.mods.kubejs.item.creativetab.CreativeTabBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CreativeModeTab extends $RegistryKubeEvent<($CreativeModeTab$0)> {
public "create"(name: StringJS): $CreativeTabBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CreativeModeTab$$Type = ($CreativeModeTab);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CreativeModeTab$$Original = $CreativeModeTab;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim" {
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTrim extends $KubeRecipe {
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTrim$$Type = ($SmithingTrim);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTrim$$Original = $SmithingTrim;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.VoidFavor" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VoidFavor extends $KubeRecipe {
public "input"(input: $Ingredient$$Type): this
public "result"(result: $ItemStack$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VoidFavor$$Type = ($VoidFavor);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VoidFavor$$Original = $VoidFavor;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ArmorMaterial" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ArmorMaterial as $ArmorMaterial$0} from "net.minecraft.world.item.ArmorMaterial"
import {$ArmorMaterialBuilder} from "dev.latvian.mods.kubejs.item.ArmorMaterialBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ArmorMaterial extends $RegistryKubeEvent<($ArmorMaterial$0)> {
public "create"(name: StringJS): $ArmorMaterialBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ArmorMaterial$$Type = ($ArmorMaterial);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ArmorMaterial$$Original = $ArmorMaterial;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.SpiritRepair" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$Item$$Type} from "net.minecraft.world.item.Item"
import {$SpiritRepairRegexData$$Type} from "com.sammy.malum.common.recipe.spirit_repair.SpiritRepairRegexData"
import {$SizedIngredient$$Type} from "net.neoforged.neoforge.common.crafting.SizedIngredient"
import {$SpiritIngredient$$Type} from "com.sammy.malum.core.systems.recipe.SpiritIngredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SpiritRepair extends $KubeRecipe {
public "validItems"(validItems: $List$$Type<((StringJS) | ($Item$$Type))>): this
public "spirits"(spirits: $List$$Type<($SpiritIngredient$$Type)>): this
public "repairMaterial"(repairMaterial: $SizedIngredient$$Type): this
public "durabilityPercentage"(durabilityPercentage: float): this
public "regex"(regex: $SpiritRepairRegexData$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SpiritRepair$$Type = ($SpiritRepair);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SpiritRepair$$Original = $SpiritRepair;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShaped$$Type = ($CraftingShaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShaped$$Original = $CraftingShaped;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CustomStat" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$CustomStatBuilder} from "dev.latvian.mods.kubejs.misc.CustomStatBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CustomStat extends $RegistryKubeEvent<($ResourceLocation)> {
public "create"(name: StringJS): $CustomStatBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomStat$$Type = ($CustomStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomStat$$Original = $CustomStat;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CampfireCooking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CampfireCooking$$Type = ($CampfireCooking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CampfireCooking$$Original = $CampfireCooking;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Potion" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Potion as $Potion$0} from "net.minecraft.world.item.alchemy.Potion"
import {$PotionBuilder} from "dev.latvian.mods.kubejs.misc.PotionBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Potion extends $RegistryKubeEvent<($Potion$0)> {
public "create"(name: StringJS): $PotionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Potion$$Type = ($Potion);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Potion$$Original = $Potion;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.SoundEvent" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SoundEventBuilder} from "dev.latvian.mods.kubejs.misc.SoundEventBuilder"
import {$SoundEvent as $SoundEvent$0} from "net.minecraft.sounds.SoundEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SoundEvent extends $RegistryKubeEvent<($SoundEvent$0)> {
public "create"(name: StringJS): $SoundEventBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoundEvent$$Type = ($SoundEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoundEvent$$Original = $SoundEvent;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Fluid" {
import {$ThickFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThickFluidBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Fluid as $Fluid$0} from "net.minecraft.world.level.material.Fluid"
import {$ThinFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThinFluidBuilder"
import {$FluidBuilder} from "dev.latvian.mods.kubejs.fluid.FluidBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Fluid extends $RegistryKubeEvent<($Fluid$0)> {
public "create"(name: StringJS): $FluidBuilder
public "create"(name: StringJS, type: "kubejs:thin"): $ThinFluidBuilder
public "create"(name: StringJS, type: "kubejs:thick"): $ThickFluidBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Fluid$$Type = ($Fluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Fluid$$Original = $Fluid;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerProfession" {
import {$VillagerProfession as $VillagerProfession$0} from "net.minecraft.world.entity.npc.VillagerProfession"
import {$VillagerProfessionBuilder} from "dev.latvian.mods.kubejs.misc.VillagerProfessionBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerProfession extends $RegistryKubeEvent<($VillagerProfession$0)> {
public "create"(name: StringJS): $VillagerProfessionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerProfession$$Type = ($VillagerProfession);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerProfession$$Original = $VillagerProfession;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.SpiritInfusion" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$SizedIngredient$$Type} from "net.neoforged.neoforge.common.crafting.SizedIngredient"
import {$SpiritIngredient$$Type} from "com.sammy.malum.core.systems.recipe.SpiritIngredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SpiritInfusion extends $KubeRecipe {
public "input"(input: $SizedIngredient$$Type): this
public "result"(result: $ItemStack$$Type): this
public "spirits"(spirits: $List$$Type<($SpiritIngredient$$Type)>): this
public "extraInputs"(extraInputs: $List$$Type<($SizedIngredient$$Type)>): this
public "carryOverComponentData"(carryOverComponentData: boolean): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SpiritInfusion$$Type = ($SpiritInfusion);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SpiritInfusion$$Original = $SpiritInfusion;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.CasterTome" {
import {$ArsComponents$Sound$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$Sound"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$ArsComponents$Color$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$Color"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CasterTome extends $KubeRecipe {
public "tomeType"(tomeType: StringJS): this
public "name"(name: StringJS): this
public "spell"(spell: $List$$Type<(StringJS)>): this
public "flavourText"(flavourText: StringJS): this
public "color"(color: $ArsComponents$Color$$Type): this
public "sound"(sound: $ArsComponents$Sound$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CasterTome$$Type = ($CasterTome);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CasterTome$$Original = $CasterTome;}
declare module "moe.wolfgirl.probejs.generated.DocumentedRecipes" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$AlchemistCauldronEmpty} from "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronEmpty"
import {$CasterTome} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.CasterTome"
import {$List$$Type} from "java.util.List"
import {$Shaped} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped"
import {$AlchemistCauldronBrew} from "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronBrew"
import {$GeasEffectType$$Type} from "com.sammy.malum.core.systems.geas.GeasEffectType"
import {$Stonecutting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$ArsComponents$CrushItem$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$CrushItem"
import {$SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"
import {$Enchantment} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Enchantment"
import {$SpiritInfusion} from "moe.wolfgirl.probejs.generated.schema.malum.SpiritInfusion"
import {$Item$$Type} from "net.minecraft.world.item.Item"
import {$SoulBinding} from "moe.wolfgirl.probejs.generated.schema.malum.SoulBinding"
import {$EnchantingApparatus} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.EnchantingApparatus"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"
import {$SpiritRepairRegexData$$Type} from "com.sammy.malum.common.recipe.spirit_repair.SpiritRepairRegexData"
import {$SmithingTransform} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform"
import {$Imbuement} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Imbuement"
import {$SpiritIngredient$$Type} from "com.sammy.malum.core.systems.recipe.SpiritIngredient"
import {$CraftingShaped} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped"
import {$Map$$Type} from "java.util.Map"
import {$UnchainedTransmutation} from "moe.wolfgirl.probejs.generated.schema.malum.UnchainedTransmutation"
import {$ArsComponents$Sound$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$Sound"
import {$Crush} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Crush"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$Blasting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting"
import {$Smelting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting"
import {$CampfireCooking} from "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking"
import {$SpiritFocusing} from "moe.wolfgirl.probejs.generated.schema.malum.SpiritFocusing"
import {$ArsComponents$Color$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$Color"
import {$Runeworking} from "moe.wolfgirl.probejs.generated.schema.malum.Runeworking"
import {$Shapeless} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless"
import {$Glyph} from "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Glyph"
import {$Smoking} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking"
import {$SmithingTrim} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim"
import {$VoidFavor} from "moe.wolfgirl.probejs.generated.schema.malum.VoidFavor"
import {$CraftingShapeless} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless"
import {$Holder$Reference$$Type} from "net.minecraft.core.Holder$Reference"
import {$AlchemistCauldronFill} from "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronFill"
import {$SizedIngredient$$Type} from "net.neoforged.neoforge.common.crafting.SizedIngredient"
import {$SpiritRepair} from "moe.wolfgirl.probejs.generated.schema.malum.SpiritRepair"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $DocumentedRecipes {
 "irons_spellbooks": {"alchemist_cauldron_brew": (results: $List$$Type<($FluidStack$$Type)>, input: $Ingredient$$Type, baseFluid: $FluidStack$$Type, byproduct?: $ItemStack$$Type) => $AlchemistCauldronBrew, "alchemist_cauldron_empty": (result: $ItemStack$$Type, input: $Ingredient$$Type, fluid: $FluidStack$$Type, sound?: $SoundEvent$$Type) => $AlchemistCauldronEmpty, "alchemist_cauldron_fill": (fluid: $FluidStack$$Type, input: $Ingredient$$Type, result: $ItemStack$$Type, mustFitAll?: boolean, sound?: $SoundEvent$$Type) => $AlchemistCauldronFill}
 "minecraft": {"crafting_shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $CraftingShapeless, "smithing_trim": (template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTrim, "crafting_shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $CraftingShaped, "blasting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Blasting, "smithing_transform": (result: $ItemStack$$Type, template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTransform, "smelting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smelting, "campfire_cooking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $CampfireCooking, "stonecutting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type) => $Stonecutting, "smoking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smoking}
 "kubejs": {"shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $Shaped, "shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $Shapeless}
 "simplyswords": {}
 "apothic_spawners": {}
 "sophisticatedbackpacks": {}
 "apotheosis": {}
 "deeperdarker": {}
 "sophisticatedstorage": {}
 "apothic_enchanting": {}
 "aether": {}
 "forbidden_arcanus": {}
 "ae2": {}
 "extendedcrafting": {}
 "undergarden": {}
 "ars_nouveau": {"imbuement": (input: $Ingredient$$Type, output: $ItemStack$$Type, source: integer, pedestalItems?: $List$$Type<($Ingredient$$Type)>) => $Imbuement, "caster_tome": (tomeType?: StringJS, name: StringJS, spell: $List$$Type<(StringJS)>, flavourText: StringJS, color: $ArsComponents$Color$$Type, sound?: $ArsComponents$Sound$$Type) => $CasterTome, "enchantment": (pedestalItems: $List$$Type<($Ingredient$$Type)>, enchantment: StringJS, level: integer, sourceCost: integer) => $Enchantment, "glyph": (output: $ItemStack$$Type, inputs: $List$$Type<($Ingredient$$Type)>, exp?: integer) => $Glyph, "crush": (input: $Ingredient$$Type, output: $List$$Type<($ArsComponents$CrushItem$$Type)>, skipBlockPlace?: boolean) => $Crush, "enchanting_apparatus": (pedestalItems?: $List$$Type<($Ingredient$$Type)>, reagent: ($List$$Type<($Ingredient$$Type)>) | ($Ingredient$$Type), result: $ItemStack$$Type, sourceCost?: integer, keepNbtOfReagent?: boolean) => $EnchantingApparatus}
 "lodestone": {}
 "paraglider": {}
 "sophisticatedcore": {}
 "twilightforest": {}
 "malum": {"unchained_transmutation": (input: $Ingredient$$Type, result: $ItemStack$$Type, group: StringJS) => $UnchainedTransmutation, "soul_binding": (input: $SizedIngredient$$Type, result: (StringJS) | ($GeasEffectType$$Type), spirits: $List$$Type<($SpiritIngredient$$Type)>, extraInputs: $List$$Type<($SizedIngredient$$Type)>) => $SoulBinding, "runeworking": (input: $SizedIngredient$$Type, secondaryInput: $SizedIngredient$$Type, result: $ItemStack$$Type, soundType?: $Holder$Reference$$Type) => $Runeworking, "void_favor": (input: $Ingredient$$Type, result: $ItemStack$$Type) => $VoidFavor, "spirit_focusing": (input: $Ingredient$$Type, result: $ItemStack$$Type, spirits: $List$$Type<($SpiritIngredient$$Type)>, time?: integer, durabilityCost?: integer) => $SpiritFocusing, "spirit_repair": (validItems: $List$$Type<((StringJS) | ($Item$$Type))>, spirits: $List$$Type<($SpiritIngredient$$Type)>, repairMaterial: $SizedIngredient$$Type, durabilityPercentage?: float, regex?: $SpiritRepairRegexData$$Type) => $SpiritRepair, "spirit_infusion": (input: $SizedIngredient$$Type, result: $ItemStack$$Type, spirits: $List$$Type<($SpiritIngredient$$Type)>, extraInputs: $List$$Type<($SizedIngredient$$Type)>, carryOverComponentData?: boolean) => $SpiritInfusion}
 "dankstorage": {}
 "storagedrawers": {}

}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DocumentedRecipes$$Type = ($DocumentedRecipes);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DocumentedRecipes$$Original = $DocumentedRecipes;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smoking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smoking$$Type = ($Smoking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smoking$$Original = $Smoking;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.MobEffect" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$MobEffectBuilder} from "dev.latvian.mods.kubejs.misc.MobEffectBuilder"
import {$MobEffect as $MobEffect$0} from "net.minecraft.world.effect.MobEffect"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $MobEffect extends $RegistryKubeEvent<($MobEffect$0)> {
public "create"(name: StringJS): $MobEffectBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MobEffect$$Type = ($MobEffect);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MobEffect$$Original = $MobEffect;}
declare module "moe.wolfgirl.probejs.generated.TagWrapperProbe" {
import {$TagWrapper} from "dev.latvian.mods.kubejs.server.tag.TagWrapper"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagWrapperProbe<T, I> extends $TagWrapper {
public "add"(...filters: (I)[]): this
public "remove"(...filters: (I)[]): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagWrapperProbe$$Type<T, I> = ($TagWrapperProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagWrapperProbe$$Original<T, I> = $TagWrapperProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronFill" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $AlchemistCauldronFill extends $KubeRecipe {
public "fluid"(fluid: $FluidStack$$Type): this
public "input"(input: $Ingredient$$Type): this
public "result"(result: $ItemStack$$Type): this
public "mustFitAll"(mustFitAll: boolean): this
public "sound"(sound: $SoundEvent$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AlchemistCauldronFill$$Type = ($AlchemistCauldronFill);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AlchemistCauldronFill$$Original = $AlchemistCauldronFill;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Glyph" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Glyph extends $KubeRecipe {
public "output"(output: $ItemStack$$Type): this
public "inputs"(inputs: $List$$Type<($Ingredient$$Type)>): this
public "exp"(exp: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Glyph$$Type = ($Glyph);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Glyph$$Original = $Glyph;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.PointOfInterestType" {
import {$PoiType} from "net.minecraft.world.entity.ai.village.poi.PoiType"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$PoiTypeBuilder} from "dev.latvian.mods.kubejs.misc.PoiTypeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $PointOfInterestType extends $RegistryKubeEvent<($PoiType)> {
public "create"(name: StringJS): $PoiTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $PointOfInterestType$$Type = ($PointOfInterestType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $PointOfInterestType$$Original = $PointOfInterestType;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Crush" {
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$ArsComponents$CrushItem$$Type} from "com.bobvarioa.kubejsarsnouveau.components.ArsComponents$CrushItem"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Crush extends $KubeRecipe {
public "input"(input: $Ingredient$$Type): this
public "output"(output: $List$$Type<($ArsComponents$CrushItem$$Type)>): this
public "skipBlockPlace"(skipBlockPlace: boolean): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Crush$$Type = ($Crush);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Crush$$Original = $Crush;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Stonecutting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Stonecutting$$Type = ($Stonecutting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Stonecutting$$Original = $Stonecutting;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$VillagerTypeBuilder} from "dev.latvian.mods.kubejs.misc.VillagerTypeBuilder"
import {$VillagerType as $VillagerType$0} from "net.minecraft.world.entity.npc.VillagerType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerType extends $RegistryKubeEvent<($VillagerType$0)> {
public "create"(name: StringJS): $VillagerTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerType$$Type = ($VillagerType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerType$$Original = $VillagerType;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Attribute" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Attribute as $Attribute$0} from "net.minecraft.world.entity.ai.attributes.Attribute"
import {$SpellAttributeBuilderJS} from "com.squoshi.irons_spells_js.entity.attribute.SpellAttributeBuilderJS"
import {$AttributeBuilder} from "dev.latvian.mods.kubejs.entity.AttributeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Attribute extends $RegistryKubeEvent<($Attribute$0)> {
public "create"(name: StringJS): $AttributeBuilder
public "create"(name: StringJS, type: "irons_spells_js:spell"): $SpellAttributeBuilderJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Attribute$$Type = ($Attribute);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Attribute$$Original = $Attribute;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Imbuement" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Imbuement extends $KubeRecipe {
public "input"(input: $Ingredient$$Type): this
public "output"(output: $ItemStack$$Type): this
public "source"(source: integer): this
public "pedestalItems"(pedestalItems: $List$$Type<($Ingredient$$Type)>): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Imbuement$$Type = ($Imbuement);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Imbuement$$Original = $Imbuement;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.UnchainedTransmutation" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $UnchainedTransmutation extends $KubeRecipe {
public "input"(input: $Ingredient$$Type): this
public "result"(result: $ItemStack$$Type): this
public "group"(group: StringJS): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $UnchainedTransmutation$$Type = ($UnchainedTransmutation);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $UnchainedTransmutation$$Original = $UnchainedTransmutation;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.Enchantment" {
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Enchantment extends $KubeRecipe {
public "pedestalItems"(pedestalItems: $List$$Type<($Ingredient$$Type)>): this
public "enchantment"(enchantment: StringJS): this
public "level"(level: integer): this
public "sourceCost"(sourceCost: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Enchantment$$Type = ($Enchantment);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Enchantment$$Original = $Enchantment;}
declare module "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronBrew" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $AlchemistCauldronBrew extends $KubeRecipe {
public "results"(results: $List$$Type<($FluidStack$$Type)>): this
public "input"(input: $Ingredient$$Type): this
public "baseFluid"(baseFluid: $FluidStack$$Type): this
public "byproduct"(byproduct: $ItemStack$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AlchemistCauldronBrew$$Type = ($AlchemistCauldronBrew);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AlchemistCauldronBrew$$Original = $AlchemistCauldronBrew;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.SoulBinding" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$GeasEffectType$$Type} from "com.sammy.malum.core.systems.geas.GeasEffectType"
import {$SizedIngredient$$Type} from "net.neoforged.neoforge.common.crafting.SizedIngredient"
import {$SpiritIngredient$$Type} from "com.sammy.malum.core.systems.recipe.SpiritIngredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SoulBinding extends $KubeRecipe {
public "input"(input: $SizedIngredient$$Type): this
public "result"(result: (StringJS) | ($GeasEffectType$$Type)): this
public "spirits"(spirits: $List$$Type<($SpiritIngredient$$Type)>): this
public "extraInputs"(extraInputs: $List$$Type<($SizedIngredient$$Type)>): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoulBinding$$Type = ($SoulBinding);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoulBinding$$Original = $SoulBinding;}
declare module "moe.wolfgirl.probejs.generated.registry.neoforge.FluidType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$FluidTypeBuilder} from "dev.latvian.mods.kubejs.fluid.FluidTypeBuilder"
import {$FluidType as $FluidType$0} from "net.neoforged.neoforge.fluids.FluidType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $FluidType extends $RegistryKubeEvent<($FluidType$0)> {
public "create"(name: StringJS): $FluidTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FluidType$$Type = ($FluidType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FluidType$$Original = $FluidType;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Block" {
import {$CarpetBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CarpetBlockBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SlabBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.SlabBlockBuilder"
import {$DoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.DoorBlockBuilder"
import {$StairBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.StairBlockBuilder"
import {$Block as $Block$0} from "net.minecraft.world.level.block.Block"
import {$PressurePlateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.PressurePlateBlockBuilder"
import {$BasicKubeBlock$Builder} from "dev.latvian.mods.kubejs.block.custom.BasicKubeBlock$Builder"
import {$CropBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CropBlockBuilder"
import {$ButtonBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.ButtonBlockBuilder"
import {$FenceBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceBlockBuilder"
import {$TrapdoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.TrapdoorBlockBuilder"
import {$WallBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.WallBlockBuilder"
import {$CardinalBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CardinalBlockBuilder"
import {$FenceGateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceGateBlockBuilder"
import {$FallingBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FallingBlockBuilder"
import {$DetectorBlock$Builder} from "dev.latvian.mods.kubejs.block.DetectorBlock$Builder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Block extends $RegistryKubeEvent<($Block$0)> {
public "create"(name: StringJS): $BasicKubeBlock$Builder
public "create"(name: StringJS, type: "kubejs:detector"): $DetectorBlock$Builder
public "create"(name: StringJS, type: "kubejs:slab"): $SlabBlockBuilder
public "create"(name: StringJS, type: "kubejs:stairs"): $StairBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence"): $FenceBlockBuilder
public "create"(name: StringJS, type: "kubejs:wall"): $WallBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence_gate"): $FenceGateBlockBuilder
public "create"(name: StringJS, type: "kubejs:pressure_plate"): $PressurePlateBlockBuilder
public "create"(name: StringJS, type: "kubejs:button"): $ButtonBlockBuilder
public "create"(name: StringJS, type: "kubejs:falling"): $FallingBlockBuilder
public "create"(name: StringJS, type: "kubejs:crop"): $CropBlockBuilder
public "create"(name: StringJS, type: "kubejs:cardinal"): $CardinalBlockBuilder
public "create"(name: StringJS, type: "kubejs:carpet"): $CarpetBlockBuilder
public "create"(name: StringJS, type: "kubejs:door"): $DoorBlockBuilder
public "create"(name: StringJS, type: "kubejs:trapdoor"): $TrapdoorBlockBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Block$$Type = ($Block);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Block$$Original = $Block;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shaped$$Type = ($Shaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shaped$$Original = $Shaped;}
declare module "moe.wolfgirl.probejs.generated.schema.irons_spellbooks.AlchemistCauldronEmpty" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $AlchemistCauldronEmpty extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "input"(input: $Ingredient$$Type): this
public "fluid"(fluid: $FluidStack$$Type): this
public "sound"(sound: $SoundEvent$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AlchemistCauldronEmpty$$Type = ($AlchemistCauldronEmpty);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AlchemistCauldronEmpty$$Original = $AlchemistCauldronEmpty;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smelting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smelting$$Type = ($Smelting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smelting$$Original = $Smelting;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shapeless$$Type = ($Shapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shapeless$$Original = $Shapeless;}
declare module "moe.wolfgirl.probejs.generated.schema.ars_nouveau.EnchantingApparatus" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $EnchantingApparatus extends $KubeRecipe {
public "pedestalItems"(pedestalItems: $List$$Type<($Ingredient$$Type)>): this
public "reagent"(reagent: ($List$$Type<($Ingredient$$Type)>) | ($Ingredient$$Type)): this
public "result"(result: $ItemStack$$Type): this
public "sourceCost"(sourceCost: integer): this
public "keepNbtOfReagent"(keepNbtOfReagent: boolean): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $EnchantingApparatus$$Type = ($EnchantingApparatus);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $EnchantingApparatus$$Original = $EnchantingApparatus;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Item" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CustomMagicSwordItem$Builder} from "com.squoshi.irons_spells_js.item.CustomMagicSwordItem$Builder"
import {$ShearsItemBuilder} from "dev.latvian.mods.kubejs.item.custom.ShearsItemBuilder"
import {$DiggerItemBuilder$Axe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Axe"
import {$CustomStaff$Builder} from "com.squoshi.irons_spells_js.item.CustomStaff$Builder"
import {$CustomSpellBook$Builder} from "com.squoshi.irons_spells_js.item.CustomSpellBook$Builder"
import {$DiggerItemBuilder$Shovel} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Shovel"
import {$ArmorItemBuilder$Boots} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Boots"
import {$SmithingTemplateItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SmithingTemplateItemBuilder"
import {$ArmorItemBuilder$Helmet} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Helmet"
import {$ArmorItemBuilder$AnimalArmor} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$AnimalArmor"
import {$SwordItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SwordItemBuilder"
import {$ArmorItemBuilder$Chestplate} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Chestplate"
import {$DiggerItemBuilder$Pickaxe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Pickaxe"
import {$DiggerItemBuilder$Hoe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Hoe"
import {$Item as $Item$0} from "net.minecraft.world.item.Item"
import {$ItemBuilder} from "dev.latvian.mods.kubejs.item.ItemBuilder"
import {$ArmorItemBuilder$Leggings} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Leggings"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Item extends $RegistryKubeEvent<($Item$0)> {
public "create"(name: StringJS): $ItemBuilder
public "create"(name: StringJS, type: "kubejs:sword"): $SwordItemBuilder
public "create"(name: StringJS, type: "kubejs:pickaxe"): $DiggerItemBuilder$Pickaxe
public "create"(name: StringJS, type: "kubejs:axe"): $DiggerItemBuilder$Axe
public "create"(name: StringJS, type: "kubejs:shovel"): $DiggerItemBuilder$Shovel
public "create"(name: StringJS, type: "kubejs:hoe"): $DiggerItemBuilder$Hoe
public "create"(name: StringJS, type: "kubejs:shears"): $ShearsItemBuilder
public "create"(name: StringJS, type: "kubejs:helmet"): $ArmorItemBuilder$Helmet
public "create"(name: StringJS, type: "kubejs:chestplate"): $ArmorItemBuilder$Chestplate
public "create"(name: StringJS, type: "kubejs:leggings"): $ArmorItemBuilder$Leggings
public "create"(name: StringJS, type: "kubejs:boots"): $ArmorItemBuilder$Boots
public "create"(name: StringJS, type: "kubejs:animal_armor"): $ArmorItemBuilder$AnimalArmor
public "create"(name: StringJS, type: "kubejs:smithing_template"): $SmithingTemplateItemBuilder
public "create"(name: StringJS, type: "irons_spells_js:magic_sword"): $CustomMagicSwordItem$Builder
public "create"(name: StringJS, type: "irons_spells_js:staff"): $CustomStaff$Builder
public "create"(name: StringJS, type: "irons_spells_js:spellbook"): $CustomSpellBook$Builder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Item$$Type = ($Item);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Item$$Original = $Item;}
declare module "moe.wolfgirl.probejs.generated.registry.irons_spellbooks.Schools" {
import {$SchoolTypeJSBuilder} from "com.squoshi.irons_spells_js.spell.school.SchoolTypeJSBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SchoolType} from "io.redspace.ironsspellbooks.api.spells.SchoolType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Schools extends $RegistryKubeEvent<($SchoolType)> {
public "create"(name: StringJS): $SchoolTypeJSBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Schools$$Type = ($Schools);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Schools$$Original = $Schools;}
declare module "moe.wolfgirl.probejs.generated.TagEventProbe" {
import {$TagWrapperProbe} from "moe.wolfgirl.probejs.generated.TagWrapperProbe"
import {$TagKubeEvent} from "dev.latvian.mods.kubejs.server.tag.TagKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagEventProbe<T, I> extends $TagKubeEvent {
public "add"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
public "remove"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagEventProbe$$Type<T, I> = ($TagEventProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagEventProbe$$Original<T, I> = $TagEventProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTransform extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTransform$$Type = ($SmithingTransform);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTransform$$Original = $SmithingTransform;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ParticleType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ParticleTypeBuilder} from "dev.latvian.mods.kubejs.misc.ParticleTypeBuilder"
import {$ParticleType as $ParticleType$0} from "net.minecraft.core.particles.ParticleType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ParticleType extends $RegistryKubeEvent<($ParticleType$0)> {
public "create"(name: StringJS): $ParticleTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleType$$Type = ($ParticleType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleType$$Original = $ParticleType;}
declare module "moe.wolfgirl.probejs.generated.schema.malum.Runeworking" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Holder$Reference$$Type} from "net.minecraft.core.Holder$Reference"
import {$SizedIngredient$$Type} from "net.neoforged.neoforge.common.crafting.SizedIngredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Runeworking extends $KubeRecipe {
public "input"(input: $SizedIngredient$$Type): this
public "secondaryInput"(secondaryInput: $SizedIngredient$$Type): this
public "result"(result: $ItemStack$$Type): this
public "soundType"(soundType: $Holder$Reference$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Runeworking$$Type = ($Runeworking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Runeworking$$Original = $Runeworking;}
