declare module "net.mehvahdjukaar.moonlight.api.item.IThirdPersonAnimationProvider" {
import {$HumanoidModel$$Type} from "net.minecraft.client.model.HumanoidModel"
import {$HumanoidArm$$Type} from "net.minecraft.world.entity.HumanoidArm"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Item$$Type} from "net.minecraft.world.item.Item"
import {$LivingEntity, $LivingEntity$$Type} from "net.minecraft.world.entity.LivingEntity"

export interface $IThirdPersonAnimationProvider$$Interface {
get "twoHanded"(): boolean
}

export class $IThirdPersonAnimationProvider implements $IThirdPersonAnimationProvider$$Interface {
static "get"(arg0: $Item$$Type): $IThirdPersonAnimationProvider
 "poseLeftArm"<T extends $LivingEntity>(arg0: $ItemStack$$Type, arg1: $HumanoidModel$$Type<(T)>, arg2: T, arg3: $HumanoidArm$$Type): boolean
 "poseRightArm"<T extends $LivingEntity>(arg0: $ItemStack$$Type, arg1: $HumanoidModel$$Type<(T)>, arg2: T, arg3: $HumanoidArm$$Type): boolean
static "attachToItem"(arg0: $Item$$Type, arg1: $IThirdPersonAnimationProvider$$Type): void
 "isTwoHanded"(): boolean
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IThirdPersonAnimationProvider$$Type = ($IThirdPersonAnimationProvider);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IThirdPersonAnimationProvider$$Original = $IThirdPersonAnimationProvider;}
declare module "net.mehvahdjukaar.moonlight.api.map.CustomMapData$Type" {
import {$StreamCodec, $StreamCodec$$Type} from "net.minecraft.network.codec.StreamCodec"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$CustomMapData} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf, $RegistryFriendlyByteBuf$$Type} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$Supplier, $Supplier$$Type} from "java.util.function.Supplier"
import {$MapItemSavedData$$Type} from "net.minecraft.world.level.saveddata.maps.MapItemSavedData"
import {$Record} from "java.lang.Record"

export class $CustomMapData$Type<P, T extends $CustomMapData<(object), (object)>> extends $Record {
static readonly "CODEC": $Codec<($CustomMapData$Type<(never), (never)>)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($CustomMapData$Type<(never), (never)>)>

constructor(id: $ResourceLocation$$Type, factory: $Supplier$$Type<(T)>, patchCodec: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (P)>)

public "get"(arg0: $MapItemSavedData$$Type): T
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "factory"(): $Supplier<(T)>
public "id"(): $ResourceLocation
public "patchCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (P)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.MoonlightCustomMapDataTypes
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.MoonlightCustomMapDataTypesTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomMapData$Type$$Type<P, T> = (Special.MoonlightCustomMapDataTypes) | ({"factory"?: $Supplier$$Type<(T)>, "patchCodec"?: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (P)>, "id"?: $ResourceLocation$$Type}) | ([factory?: $Supplier$$Type<(T)>, patchCodec?: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (P)>, id?: $ResourceLocation$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomMapData$Type$$Original<P, T> = $CustomMapData$Type<(P), (T)>;}
declare module "net.mehvahdjukaar.moonlight.api.events.IDropItemOnDeathEvent" {
import {$Player, $Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$SimpleEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.SimpleEvent"

export interface $IDropItemOnDeathEvent$$Interface extends $SimpleEvent$$Interface {
get "beforeDrop"(): boolean
set "returnItemStack"(value: $ItemStack$$Type)
get "returnItemStack"(): $ItemStack
set "canceled"(value: boolean)
get "player"(): $Player
get "canceled"(): boolean
get "itemStack"(): $ItemStack
}

export class $IDropItemOnDeathEvent implements $IDropItemOnDeathEvent$$Interface {
static "create"(arg0: $ItemStack$$Type, arg1: $Player$$Type, arg2: boolean): $IDropItemOnDeathEvent
 "isBeforeDrop"(): boolean
 "setReturnItemStack"(arg0: $ItemStack$$Type): void
 "getReturnItemStack"(): $ItemStack
 "setCanceled"(arg0: boolean): void
 "getPlayer"(): $Player
 "isCanceled"(): boolean
 "getItemStack"(): $ItemStack
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IDropItemOnDeathEvent$$Type = ($IDropItemOnDeathEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IDropItemOnDeathEvent$$Original = $IDropItemOnDeathEvent;}
declare module "net.mehvahdjukaar.moonlight.api.events.platform.FireConsumeBlockEvent" {
import {$BlockEvent} from "net.neoforged.neoforge.event.level.BlockEvent"
import {$Direction, $Direction$$Type} from "net.minecraft.core.Direction"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$IFireConsumeBlockEvent, $IFireConsumeBlockEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.IFireConsumeBlockEvent"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LevelAccessor} from "net.minecraft.world.level.LevelAccessor"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $FireConsumeBlockEvent extends $BlockEvent implements $IFireConsumeBlockEvent$$Interface {
constructor(arg0: $Level$$Type, arg1: $BlockPos$$Type, arg2: $BlockState$$Type, arg3: integer, arg4: integer, arg5: $Direction$$Type, arg6: boolean)

public "wasReplacedByFire"(): boolean
public "getFace"(): $Direction
public "getChance"(): integer
public "getAge"(): integer
public "getFinalState"(): $BlockState
public "setFinalState"(arg0: $BlockState$$Type): void
public "getState"(): $BlockState
public static "create"(arg0: $BlockPos$$Type, arg1: $Level$$Type, arg2: $BlockState$$Type, arg3: integer, arg4: integer, arg5: $Direction$$Type, arg6: boolean): $IFireConsumeBlockEvent
public "getLevel"(): $LevelAccessor
public "getPos"(): $BlockPos
get "face"(): $Direction
get "chance"(): integer
get "age"(): integer
get "finalState"(): $BlockState
set "finalState"(value: $BlockState$$Type)
get "state"(): $BlockState
get "level"(): $LevelAccessor
get "pos"(): $BlockPos
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FireConsumeBlockEvent$$Type = ($FireConsumeBlockEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FireConsumeBlockEvent$$Original = $FireConsumeBlockEvent;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.FoodProvider" {
import {$Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map} from "java.util.Map"
import {$Codec} from "com.mojang.serialization.Codec"
import {$Item, $Item$$Type} from "net.minecraft.world.item.Item"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$Consumer$$Type} from "java.util.function.Consumer"

export class $FoodProvider {
static readonly "CODEC": $Codec<($FoodProvider)>
static readonly "CUSTOM_PROVIDERS": $Map<($Item), ($FoodProvider)>
static readonly "EMPTY": $FoodProvider

public "isEmpty"(): boolean
public static "create"(arg0: $Item$$Type, arg1: integer): $FoodProvider
public "consume"(arg0: $Player$$Type, arg1: $Level$$Type, arg2: $Consumer$$Type<($ItemStack)>): boolean
public "getDivider"(): integer
public "getFoodItem"(): $Item
get "empty"(): boolean
get "divider"(): integer
get "foodItem"(): $Item
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FoodProvider$$Type = ($FoodProvider);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FoodProvider$$Original = $FoodProvider;}
declare module "net.mehvahdjukaar.moonlight.api.worldgen.SpawnBoxSettings" {
import {$Map, $Map$$Type} from "java.util.Map"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MobCategory, $MobCategory$$Type} from "net.minecraft.world.entity.MobCategory"
import {$WeightedRandomList, $WeightedRandomList$$Type} from "net.minecraft.util.random.WeightedRandomList"
import {$MobSpawnSettings$SpawnerData, $MobSpawnSettings$SpawnerData$$Type} from "net.minecraft.world.level.biome.MobSpawnSettings$SpawnerData"
import {$Record} from "java.lang.Record"

export class $SpawnBoxSettings extends $Record {
static readonly "CODEC": $Codec<($SpawnBoxSettings)>
static readonly "EMPTY": $SpawnBoxSettings

constructor(spawnOverrides: $Map$$Type<($MobCategory$$Type), ($Map$$Type<(StringJS), ($WeightedRandomList$$Type<($MobSpawnSettings$SpawnerData$$Type)>)>)>)

public "get"(arg0: StringJS, arg1: $MobCategory$$Type): $WeightedRandomList<($MobSpawnSettings$SpawnerData)>
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "isEmpty"(): boolean
public "hasCategory"(arg0: $MobCategory$$Type): boolean
public "spawnOverrides"(): $Map<($MobCategory), ($Map<(StringJS), ($WeightedRandomList<($MobSpawnSettings$SpawnerData)>)>)>
get "empty"(): boolean
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SpawnBoxSettings$$Type = ({"spawnOverrides"?: $Map$$Type<($MobCategory$$Type), ($Map$$Type<(StringJS), ($WeightedRandomList$$Type<($MobSpawnSettings$SpawnerData$$Type)>)>)>}) | ([spawnOverrides?: $Map$$Type<($MobCategory$$Type), ($Map$$Type<(StringJS), ($WeightedRandomList$$Type<($MobSpawnSettings$SpawnerData$$Type)>)>)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SpawnBoxSettings$$Original = $SpawnBoxSettings;}
declare module "net.mehvahdjukaar.moonlight.api.events.platform.VillagerBrainEvent" {
import {$Map} from "java.util.Map"
import {$Brain$$Type} from "net.minecraft.world.entity.ai.Brain"
import {$MemoryModuleType} from "net.minecraft.world.entity.ai.memory.MemoryModuleType"
import {$Optional} from "java.util.Optional"
import {$Pair, $Pair$$Type} from "com.mojang.datafixers.util.Pair"
import {$SensorType$$Type} from "net.minecraft.world.entity.ai.sensing.SensorType"
import {$Event} from "net.neoforged.bus.api.Event"
import {$ImmutableList$$Type} from "com.google.common.collect.ImmutableList"
import {$Villager, $Villager$$Type} from "net.minecraft.world.entity.npc.Villager"
import {$Sensor$$Type} from "net.minecraft.world.entity.ai.sensing.Sensor"
import {$IVillagerBrainEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.IVillagerBrainEvent"
import {$BehaviorControl$$Type} from "net.minecraft.world.entity.ai.behavior.BehaviorControl"
import {$ExpirableValue} from "net.minecraft.world.entity.ai.memory.ExpirableValue"
import {$Activity$$Type} from "net.minecraft.world.entity.schedule.Activity"
import {$VillagerBrainEventInternal} from "net.mehvahdjukaar.moonlight.core.misc.VillagerBrainEventInternal"

export class $VillagerBrainEvent extends $Event implements $IVillagerBrainEvent$$Interface {
constructor(arg0: $Brain$$Type<($Villager$$Type)>, arg1: $Villager$$Type)

public "getVillager"(): $Villager
public "scheduleActivity"(arg0: $Activity$$Type, arg1: integer, arg2: integer): void
public "getMemories"(): $Map<($MemoryModuleType<(never)>), ($Optional<($ExpirableValue<(never)>)>)>
public "addTaskToActivity"<P extends $Pair<(object), (object)>>(arg0: $Activity$$Type, arg1: P): boolean
public "addSensor"(arg0: $SensorType$$Type<($Sensor$$Type<($Villager$$Type)>)>): void
public "getInternal"(): $VillagerBrainEventInternal
public "addOrReplaceActivity"(arg0: $Activity$$Type, arg1: $ImmutableList$$Type<($Pair$$Type<(integer), ($BehaviorControl$$Type<($Villager$$Type)>)>)>): void
get "villager"(): $Villager
get "memories"(): $Map<($MemoryModuleType<(never)>), ($Optional<($ExpirableValue<(never)>)>)>
get "internal"(): $VillagerBrainEventInternal
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerBrainEvent$$Type = ($VillagerBrainEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerBrainEvent$$Original = $VillagerBrainEvent;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.SoftFluid" {
import {$FoodProvider} from "net.mehvahdjukaar.moonlight.api.fluids.FoodProvider"
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Optional} from "java.util.Optional"
import {$FluidContainerList} from "net.mehvahdjukaar.moonlight.api.fluids.FluidContainerList"
import {$Pair} from "com.mojang.datafixers.util.Pair"
import {$SoftFluid$TintMethod} from "net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$TintMethod"
import {$Component} from "net.minecraft.network.chat.Component"
import {$DataComponentType} from "net.minecraft.core.component.DataComponentType"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Fluid, $Fluid$$Type} from "net.minecraft.world.level.material.Fluid"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$Item, $Item$$Type} from "net.minecraft.world.item.Item"
import {$HolderSet} from "net.minecraft.core.HolderSet"
import {$Triplet} from "net.mehvahdjukaar.moonlight.api.misc.Triplet"

export class $SoftFluid {
static readonly "BOTTLE_COUNT": integer
readonly "isGenerated": boolean
static readonly "CODEC": $Codec<($SoftFluid)>
static readonly "BUCKET_COUNT": integer
static readonly "HOLDER_CODEC": $Codec<($Holder<($SoftFluid)>)>
static readonly "TRANSLATABLE_COMPONENT": $Codec<($Component)>
static readonly "BOWL_COUNT": integer
static readonly "WATER_BUCKET_COUNT": integer
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($Holder<($SoftFluid)>)>

constructor(arg0: $Holder$$Type<($Fluid)>)

public "isEnabled"(): boolean
/**
 * 
 * @deprecated
 */
public "isEmptyFluid"(): boolean
public "getEmissivity"(): integer
public "getLuminosity"(): integer
public "getFoodProvider"(): $FoodProvider
public "getVanillaFluid"(): $Holder<($Fluid)>
public "getFilledContainer"(arg0: $Item$$Type): $Optional<($Item)>
public "getTintMethod"(): $SoftFluid$TintMethod
public "getTextureOverride"(): $ResourceLocation
public static "getRenderingData"(arg0: $ResourceLocation$$Type): $Triplet<($ResourceLocation), ($ResourceLocation), (integer)>
public "isEquivalent"(arg0: $Holder$$Type<($Fluid)>): boolean
public "isColored"(): boolean
public static "getFluidSpecificAttributes"(arg0: $Fluid$$Type): $Pair<(integer), ($Component)>
public "getAverageTextureTintColor"(): integer
public "getEquivalentFluids"(): $HolderSet<($Fluid)>
public "getPreservedComponents"(): $HolderSet<($DataComponentType<(never)>)>
public "getEmptyContainer"(arg0: $Item$$Type): $Optional<($Item)>
public "getContainerList"(): $FluidContainerList
public "isFood"(): boolean
public "getTintColor"(): integer
public "getStillTexture"(): $ResourceLocation
public "getFlowingTexture"(): $ResourceLocation
public "getTranslatedName"(): $Component
public "afterInit"(): void
get "enabled"(): boolean
get "emptyFluid"(): boolean
get "emissivity"(): integer
get "luminosity"(): integer
get "foodProvider"(): $FoodProvider
get "vanillaFluid"(): $Holder<($Fluid)>
get "tintMethod"(): $SoftFluid$TintMethod
get "textureOverride"(): $ResourceLocation
get "colored"(): boolean
get "averageTextureTintColor"(): integer
get "equivalentFluids"(): $HolderSet<($Fluid)>
get "preservedComponents"(): $HolderSet<($DataComponentType<(never)>)>
get "containerList"(): $FluidContainerList
get "food"(): boolean
get "tintColor"(): integer
get "stillTexture"(): $ResourceLocation
get "flowingTexture"(): $ResourceLocation
get "translatedName"(): $Component
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.MoonlightSoftFluid
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.MoonlightSoftFluidTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoftFluid$$Type = (Special.MoonlightSoftFluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoftFluid$$Original = $SoftFluid;}
declare module "net.mehvahdjukaar.moonlight.api.misc.Triplet" {
import {$Record} from "java.lang.Record"

export class $Triplet<L, M, R> extends $Record {
constructor(left: L, middle: M, right: R)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public static "of"<A, B, C>(arg0: A, arg1: B, arg2: C): $Triplet<(A), (B), (C)>
public "left"(): L
public "right"(): R
public "middle"(): M
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Triplet$$Type<L, M, R> = ({"right"?: R, "left"?: L, "middle"?: M}) | ([right?: R, left?: L, middle?: M]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Triplet$$Original<L, M, R> = $Triplet<(L), (M), (R)>;}
declare module "net.mehvahdjukaar.moonlight.api.map.CustomMapData" {
import {$CustomMapData$Type} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData$Type"
import {$CompoundTag$$Type} from "net.minecraft.nbt.CompoundTag"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$CustomMapData$DirtyCounter, $CustomMapData$DirtyCounter$$Type} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData$DirtyCounter"
import {$Component} from "net.minecraft.network.chat.Component"
import {$Entity$$Type} from "net.minecraft.world.entity.Entity"
import {$HolderLookup$Provider$$Type} from "net.minecraft.core.HolderLookup$Provider"
import {$MapItemSavedData$$Type} from "net.minecraft.world.level.saveddata.maps.MapItemSavedData"
import {$Consumer$$Type} from "java.util.function.Consumer"

export interface $CustomMapData$$Interface<C extends $CustomMapData$DirtyCounter, P> {
get "type"(): $CustomMapData$Type<(P), (never)>
}

export class $CustomMapData<C extends $CustomMapData$DirtyCounter, P> implements $CustomMapData$$Interface {
 "load"(arg0: $CompoundTag$$Type, arg1: $HolderLookup$Provider$$Type): void
 "save"(arg0: $CompoundTag$$Type, arg1: $HolderLookup$Provider$$Type): void
 "getType"(): $CustomMapData$Type<(P), (never)>
 "persistOnCopyOrLock"(): boolean
 "onItemUpdate"(arg0: $MapItemSavedData$$Type, arg1: $Entity$$Type): boolean
 "setDirty"(arg0: $MapItemSavedData$$Type, arg1: $Consumer$$Type<(C)>): void
 "onItemTooltip"(arg0: $MapItemSavedData$$Type, arg1: $ItemStack$$Type): $Component
 "createUpdatePatch"(arg0: C): P
 "applyUpdatePatch"(arg0: P): void
 "persistOnRescale"(): boolean
 "createDirtyCounter"(): C
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomMapData$$Type<C, P> = ($CustomMapData<(C), (P)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomMapData$$Original<C, P> = $CustomMapData<(C), (P)>;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.FluidContainerList" {
import {$Iterable$$Interface} from "java.lang.Iterable"
import {$Iterator} from "java.util.Iterator"
import {$Collection} from "java.util.Collection"
import {$FluidContainerList$Category, $FluidContainerList$Category$$Type} from "net.mehvahdjukaar.moonlight.api.fluids.FluidContainerList$Category"
import {$Optional} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$Spliterator} from "java.util.Spliterator"
import {$List, $List$$Type} from "java.util.List"
import {$Item, $Item$$Type} from "net.minecraft.world.item.Item"
import {$Consumer$$Type} from "java.util.function.Consumer"

export class $FluidContainerList implements $Iterable$$Interface<($FluidContainerList$Category)> {
static readonly "CODEC": $Codec<($FluidContainerList)>

constructor(arg0: $List$$Type<($FluidContainerList$Category$$Type)>)
constructor()

public "iterator"(): $Iterator<($FluidContainerList$Category)>
public "getPossibleFilled"(): $Collection<($Item)>
public "getFilled"(arg0: $Item$$Type): $Optional<($Item)>
public "getEmpty"(arg0: $Item$$Type): $Optional<($Item)>
public "getCategoryFromFilled"(arg0: $Item$$Type): $Optional<($FluidContainerList$Category)>
public "getCategoryFromEmpty"(arg0: $Item$$Type): $Optional<($FluidContainerList$Category)>
public "getPossibleEmpty"(): $Collection<($Item)>
public "getCategories"(): $List<($FluidContainerList$Category)>
public "spliterator"(): $Spliterator<($FluidContainerList$Category)>
public "forEach"(arg0: $Consumer$$Type<($FluidContainerList$Category)>): void
[Symbol.iterator](): IterableIterator<$FluidContainerList$Category>;
get "possibleFilled"(): $Collection<($Item)>
get "possibleEmpty"(): $Collection<($Item)>
get "categories"(): $List<($FluidContainerList$Category)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FluidContainerList$$Type = ($FluidContainerList);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FluidContainerList$$Original = $FluidContainerList;}
declare module "net.mehvahdjukaar.moonlight.api.misc.WorldSavedData" {
import {$WorldSavedDataType} from "net.mehvahdjukaar.moonlight.api.misc.WorldSavedDataType"
import {$CompoundTag, $CompoundTag$$Type} from "net.minecraft.nbt.CompoundTag"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$SavedData} from "net.minecraft.world.level.saveddata.SavedData"
import {$HolderLookup$Provider$$Type} from "net.minecraft.core.HolderLookup$Provider"

export class $WorldSavedData extends $SavedData {
constructor()

public "save"(arg0: $CompoundTag$$Type, arg1: $HolderLookup$Provider$$Type): $CompoundTag
public "getType"(): $WorldSavedDataType<($WorldSavedData)>
public "sync"(): void
public "setDirty"(arg0: boolean): void
public "onReassigned"(arg0: $Level$$Type): void
get "type"(): $WorldSavedDataType<($WorldSavedData)>
set "dirty"(value: boolean)
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WorldSavedData$$Type = ($WorldSavedData);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WorldSavedData$$Original = $WorldSavedData;}
declare module "net.mehvahdjukaar.moonlight.api.events.ILightningStruckBlockEvent" {
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LightningBolt, $LightningBolt$$Type} from "net.minecraft.world.entity.LightningBolt"
import {$LevelAccessor, $LevelAccessor$$Type} from "net.minecraft.world.level.LevelAccessor"
import {$SimpleEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.SimpleEvent"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export interface $ILightningStruckBlockEvent$$Interface extends $SimpleEvent$$Interface {
get "state"(): $BlockState
get "level"(): $LevelAccessor
get "entity"(): $LightningBolt
get "pos"(): $BlockPos
}

export class $ILightningStruckBlockEvent implements $ILightningStruckBlockEvent$$Interface {
 "getState"(): $BlockState
static "create"(arg0: $BlockState$$Type, arg1: $LevelAccessor$$Type, arg2: $BlockPos$$Type, arg3: $LightningBolt$$Type): $ILightningStruckBlockEvent
 "getLevel"(): $LevelAccessor
 "getEntity"(): $LightningBolt
 "getPos"(): $BlockPos
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ILightningStruckBlockEvent$$Type = ($ILightningStruckBlockEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ILightningStruckBlockEvent$$Original = $ILightningStruckBlockEvent;}
declare module "net.mehvahdjukaar.moonlight.api.client.ModFluidRenderProperties" {
import {$PoseStack$$Type} from "com.mojang.blaze3d.vertex.PoseStack"
import {$VertexConsumer$$Type} from "com.mojang.blaze3d.vertex.VertexConsumer"
import {$Vector3f, $Vector3f$$Type} from "org.joml.Vector3f"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$Camera$$Type} from "net.minecraft.client.Camera"
import {$FogShape$$Type} from "com.mojang.blaze3d.shaders.FogShape"
import {$ClientLevel$$Type} from "net.minecraft.client.multiplayer.ClientLevel"
import {$Fluid$$Type} from "net.minecraft.world.level.material.Fluid"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$BlockAndTintGetter$$Type} from "net.minecraft.world.level.BlockAndTintGetter"
import {$IClientFluidTypeExtensions, $IClientFluidTypeExtensions$$Interface} from "net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions"
import {$Minecraft$$Type} from "net.minecraft.client.Minecraft"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$FluidState$$Type} from "net.minecraft.world.level.material.FluidState"
import {$FluidType$$Type} from "net.neoforged.neoforge.fluids.FluidType"
import {$FogRenderer$FogMode$$Type} from "net.minecraft.client.renderer.FogRenderer$FogMode"
import {$BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $ModFluidRenderProperties implements $IClientFluidTypeExtensions$$Interface {
constructor(arg0: $ResourceLocation$$Type, arg1: $ResourceLocation$$Type)
constructor(arg0: $ResourceLocation$$Type, arg1: $ResourceLocation$$Type, arg2: integer)

public "getOverlayTexture"(): $ResourceLocation
public "getOverlayTexture"(arg0: $FluidState$$Type, arg1: $BlockAndTintGetter$$Type, arg2: $BlockPos$$Type): $ResourceLocation
public "modifyFogRender"(arg0: $Camera$$Type, arg1: $FogRenderer$FogMode$$Type, arg2: float, arg3: float, arg4: float, arg5: float, arg6: $FogShape$$Type): void
public "getTintColor"(arg0: $FluidState$$Type, arg1: $BlockAndTintGetter$$Type, arg2: $BlockPos$$Type): integer
public "getTintColor"(): integer
public "modifyFogColor"(arg0: $Camera$$Type, arg1: float, arg2: $ClientLevel$$Type, arg3: integer, arg4: float, arg5: $Vector3f$$Type): $Vector3f
public "getStillTexture"(): $ResourceLocation
public "getStillTexture"(arg0: $FluidState$$Type, arg1: $BlockAndTintGetter$$Type, arg2: $BlockPos$$Type): $ResourceLocation
public "getFlowingTexture"(arg0: $FluidState$$Type, arg1: $BlockAndTintGetter$$Type, arg2: $BlockPos$$Type): $ResourceLocation
public "getFlowingTexture"(): $ResourceLocation
public "getRenderOverlayTexture"(arg0: $Minecraft$$Type): $ResourceLocation
public static "of"(arg0: $FluidState$$Type): $IClientFluidTypeExtensions
public static "of"(arg0: $FluidType$$Type): $IClientFluidTypeExtensions
public static "of"(arg0: $Fluid$$Type): $IClientFluidTypeExtensions
public "getOverlayTexture"(arg0: $FluidStack$$Type): $ResourceLocation
public "getTintColor"(arg0: $FluidStack$$Type): integer
public "getStillTexture"(arg0: $FluidStack$$Type): $ResourceLocation
public "renderOverlay"(arg0: $Minecraft$$Type, arg1: $PoseStack$$Type): void
public "renderFluid"(arg0: $FluidState$$Type, arg1: $BlockAndTintGetter$$Type, arg2: $BlockPos$$Type, arg3: $VertexConsumer$$Type, arg4: $BlockState$$Type): boolean
public "getFlowingTexture"(arg0: $FluidStack$$Type): $ResourceLocation
get "overlayTexture"(): $ResourceLocation
get "tintColor"(): integer
get "stillTexture"(): $ResourceLocation
get "flowingTexture"(): $ResourceLocation
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ModFluidRenderProperties$$Type = ($ModFluidRenderProperties);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ModFluidRenderProperties$$Original = $ModFluidRenderProperties;}
declare module "net.mehvahdjukaar.moonlight.api.events.IVillagerBrainEvent" {
import {$Map} from "java.util.Map"
import {$MemoryModuleType} from "net.minecraft.world.entity.ai.memory.MemoryModuleType"
import {$Optional} from "java.util.Optional"
import {$Pair, $Pair$$Type} from "com.mojang.datafixers.util.Pair"
import {$SensorType$$Type} from "net.minecraft.world.entity.ai.sensing.SensorType"
import {$ImmutableList$$Type} from "com.google.common.collect.ImmutableList"
import {$Villager, $Villager$$Type} from "net.minecraft.world.entity.npc.Villager"
import {$Sensor$$Type} from "net.minecraft.world.entity.ai.sensing.Sensor"
import {$BehaviorControl$$Type} from "net.minecraft.world.entity.ai.behavior.BehaviorControl"
import {$ExpirableValue} from "net.minecraft.world.entity.ai.memory.ExpirableValue"
import {$Activity$$Type} from "net.minecraft.world.entity.schedule.Activity"
import {$VillagerBrainEventInternal} from "net.mehvahdjukaar.moonlight.core.misc.VillagerBrainEventInternal"
import {$SimpleEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.SimpleEvent"

export interface $IVillagerBrainEvent$$Interface extends $SimpleEvent$$Interface {
get "villager"(): $Villager
get "memories"(): $Map<($MemoryModuleType<(never)>), ($Optional<($ExpirableValue<(never)>)>)>
get "internal"(): $VillagerBrainEventInternal
}

export class $IVillagerBrainEvent implements $IVillagerBrainEvent$$Interface {
 "getVillager"(): $Villager
 "scheduleActivity"(arg0: $Activity$$Type, arg1: integer, arg2: integer): void
 "getMemories"(): $Map<($MemoryModuleType<(never)>), ($Optional<($ExpirableValue<(never)>)>)>
 "addTaskToActivity"<P extends $Pair<(object), (object)>>(arg0: $Activity$$Type, arg1: P): boolean
 "addSensor"(arg0: $SensorType$$Type<($Sensor$$Type<($Villager$$Type)>)>): void
 "getInternal"(): $VillagerBrainEventInternal
 "addOrReplaceActivity"(arg0: $Activity$$Type, arg1: $ImmutableList$$Type<($Pair$$Type<(integer), ($BehaviorControl$$Type<($Villager$$Type)>)>)>): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IVillagerBrainEvent$$Type = ($IVillagerBrainEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IVillagerBrainEvent$$Original = $IVillagerBrainEvent;}
declare module "net.mehvahdjukaar.moonlight.api.events.platform.LightningStruckBlockEvent" {
import {$BlockEvent} from "net.neoforged.neoforge.event.level.BlockEvent"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LightningBolt, $LightningBolt$$Type} from "net.minecraft.world.entity.LightningBolt"
import {$LevelAccessor, $LevelAccessor$$Type} from "net.minecraft.world.level.LevelAccessor"
import {$ILightningStruckBlockEvent, $ILightningStruckBlockEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.ILightningStruckBlockEvent"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $LightningStruckBlockEvent extends $BlockEvent implements $ILightningStruckBlockEvent$$Interface {
constructor(arg0: $BlockState$$Type, arg1: $LevelAccessor$$Type, arg2: $BlockPos$$Type, arg3: $LightningBolt$$Type)

public "getEntity"(): $LightningBolt
public "getState"(): $BlockState
public static "create"(arg0: $BlockState$$Type, arg1: $LevelAccessor$$Type, arg2: $BlockPos$$Type, arg3: $LightningBolt$$Type): $ILightningStruckBlockEvent
public "getLevel"(): $LevelAccessor
public "getPos"(): $BlockPos
get "entity"(): $LightningBolt
get "state"(): $BlockState
get "level"(): $LevelAccessor
get "pos"(): $BlockPos
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $LightningStruckBlockEvent$$Type = ($LightningStruckBlockEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $LightningStruckBlockEvent$$Original = $LightningStruckBlockEvent;}
declare module "net.mehvahdjukaar.moonlight.api.map.ExpandedMapData" {
import {$CustomMapData$Type, $CustomMapData$Type$$Type} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData$Type"
import {$Map} from "java.util.Map"
import {$CustomMapData} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData"
import {$CustomMapData$DirtyCounter} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData$DirtyCounter"
import {$MLMapMarker, $MLMapMarker$$Type} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapMarker"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LevelAccessor$$Type} from "net.minecraft.world.level.LevelAccessor"
import {$MapItemSavedData} from "net.minecraft.world.level.saveddata.maps.MapItemSavedData"
import {$MLMapDecoration} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration"
import {$Consumer$$Type} from "java.util.function.Consumer"

export interface $ExpandedMapData$$Interface {
}

export class $ExpandedMapData implements $ExpandedMapData$$Interface {
 "ml$setCustomDataDirty"<H extends $CustomMapData$DirtyCounter>(arg0: $CustomMapData$Type$$Type<(never), (never)>, arg1: $Consumer$$Type<(H)>): void
 "ml$getCustomData"(): $Map<($CustomMapData$Type<(never), (never)>), ($CustomMapData<(never), (never)>)>
 "ml$getCustomMarkers"(): $Map<(StringJS), ($MLMapMarker<(never)>)>
 "ml$removeCustomMarker"(arg0: StringJS): boolean
 "ml$resetCustomDecoration"(): void
 "ml$toggleCustomDecoration"(arg0: $LevelAccessor$$Type, arg1: $BlockPos$$Type): boolean
 "ml$addCustomMarker"<M extends $MLMapMarker<(object)>>(arg0: M): void
 "ml$setCustomDecorationsDirty"(): void
 "ml$getVanillaDecorationSize"(): integer
 "ml$getCustomDecorations"(): $Map<(StringJS), ($MLMapDecoration)>
 "ml$copy"(): $MapItemSavedData
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ExpandedMapData$$Type = ($ExpandedMapData);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ExpandedMapData$$Original = $ExpandedMapData;}
declare module "net.mehvahdjukaar.moonlight.api.worldgen.ISpawnBoxStructure" {
import {$SpawnBoxSettings, $SpawnBoxSettings$$Type} from "net.mehvahdjukaar.moonlight.api.worldgen.SpawnBoxSettings"
import {$MobCategory$$Type} from "net.minecraft.world.entity.MobCategory"
import {$Structure$$Type} from "net.minecraft.world.level.levelgen.structure.Structure"
import {$LongSet$$Type} from "it.unimi.dsi.fastutil.longs.LongSet"
import {$WeightedRandomList} from "net.minecraft.util.random.WeightedRandomList"
import {$StructureManager$$Type} from "net.minecraft.world.level.StructureManager"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$MobSpawnSettings$SpawnerData} from "net.minecraft.world.level.biome.MobSpawnSettings$SpawnerData"
import {$ISpecialSpawnsStructure$$Interface} from "net.mehvahdjukaar.moonlight.api.worldgen.ISpecialSpawnsStructure"

export interface $ISpawnBoxStructure$$Interface extends $ISpecialSpawnsStructure$$Interface {

(): $SpawnBoxSettings$$Type
}

export class $ISpawnBoxStructure implements $ISpawnBoxStructure$$Interface {
 "ml$getSpecialSpawns"(arg0: $StructureManager$$Type, arg1: $Structure$$Type, arg2: $BlockPos$$Type, arg3: $LongSet$$Type, arg4: $MobCategory$$Type): $WeightedRandomList<($MobSpawnSettings$SpawnerData)>
 "ml$getSpawnBoxSettings"(): $SpawnBoxSettings
 "ml$setSpawnBoxSettings"(arg0: $SpawnBoxSettings$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ISpawnBoxStructure$$Type = (() => $SpawnBoxSettings$$Type);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ISpawnBoxStructure$$Original = $ISpawnBoxStructure;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.ModFlowingFluid$Properties" {
import {$Map} from "java.util.Map"
import {$PathType$$Type} from "net.minecraft.world.level.pathfinder.PathType"
import {$Rarity$$Type} from "net.minecraft.world.item.Rarity"
import {$SoundEvent, $SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"

export class $ModFlowingFluid$Properties {
 "canConvertToSource": boolean
 "sounds": $Map<(StringJS), ($SoundEvent)>

constructor()

public "rarity"(arg0: $Rarity$$Type): $ModFlowingFluid$Properties
public "motionScale"(arg0: double): $ModFlowingFluid$Properties
public "canPushEntity"(arg0: boolean): $ModFlowingFluid$Properties
public "canExtinguish"(arg0: boolean): $ModFlowingFluid$Properties
public "descriptionId"(arg0: StringJS): $ModFlowingFluid$Properties
public "temperature"(arg0: integer): $ModFlowingFluid$Properties
public "supportsBoating"(arg0: boolean): $ModFlowingFluid$Properties
public "lightLevel"(arg0: integer): $ModFlowingFluid$Properties
public "canSwim"(arg0: boolean): $ModFlowingFluid$Properties
public "fallDistanceModifier"(arg0: float): $ModFlowingFluid$Properties
public "adjacentPathType"(arg0: $PathType$$Type): $ModFlowingFluid$Properties
public "sound"(arg0: StringJS, arg1: $SoundEvent$$Type): $ModFlowingFluid$Properties
public "canHydrate"(arg0: boolean): $ModFlowingFluid$Properties
public "setCanConvertToSource"(arg0: boolean): $ModFlowingFluid$Properties
public "viscosity"(arg0: integer): $ModFlowingFluid$Properties
public "pathType"(arg0: $PathType$$Type): $ModFlowingFluid$Properties
public "canDrown"(arg0: boolean): $ModFlowingFluid$Properties
public "density"(arg0: integer): $ModFlowingFluid$Properties
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ModFlowingFluid$Properties$$Type = ($ModFlowingFluid$Properties);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ModFlowingFluid$Properties$$Original = $ModFlowingFluid$Properties;}
declare module "net.mehvahdjukaar.moonlight.api.events.platform.DropItemOnDeathEvent" {
import {$IDropItemOnDeathEvent, $IDropItemOnDeathEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.IDropItemOnDeathEvent"
import {$Player, $Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ICancellableEvent$$Interface} from "net.neoforged.bus.api.ICancellableEvent"
import {$Event} from "net.neoforged.bus.api.Event"

export class $DropItemOnDeathEvent extends $Event implements $IDropItemOnDeathEvent$$Interface, $ICancellableEvent$$Interface {
constructor(arg0: $ItemStack$$Type, arg1: $Player$$Type, arg2: boolean)

public static "create"(arg0: $ItemStack$$Type, arg1: $Player$$Type, arg2: boolean): $IDropItemOnDeathEvent
public "isBeforeDrop"(): boolean
public "setReturnItemStack"(arg0: $ItemStack$$Type): void
public "getReturnItemStack"(): $ItemStack
public "setCanceled"(arg0: boolean): void
public "getPlayer"(): $Player
public "isCanceled"(): boolean
public "getItemStack"(): $ItemStack
get "beforeDrop"(): boolean
set "returnItemStack"(value: $ItemStack$$Type)
get "returnItemStack"(): $ItemStack
set "canceled"(value: boolean)
get "player"(): $Player
get "canceled"(): boolean
get "itemStack"(): $ItemStack
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DropItemOnDeathEvent$$Type = ($DropItemOnDeathEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DropItemOnDeathEvent$$Original = $DropItemOnDeathEvent;}
declare module "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Optional$$Type} from "java.util.Optional"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$MLMapDecorationType, $MLMapDecorationType$$Type} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"

export class $MLMapDecoration {
static readonly "CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($MLMapDecoration)>

constructor(arg0: $Holder$$Type<($MLMapDecorationType<(never), (never)>)>, arg1: byte, arg2: byte, arg3: byte, arg4: ($Component$$Type)?)

public "equals"(arg0: any): boolean
public "hashCode"(): integer
public "getType"(): $Holder<($MLMapDecorationType<(never), (never)>)>
public "getDisplayName"(): $Component
public "getY"(): byte
public "getRot"(): byte
public "getX"(): byte
get "type"(): $Holder<($MLMapDecorationType<(never), (never)>)>
get "displayName"(): $Component
get "y"(): byte
get "rot"(): byte
get "x"(): byte
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MLMapDecoration$$Type = ($MLMapDecoration);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MLMapDecoration$$Original = $MLMapDecoration;}
declare module "net.mehvahdjukaar.moonlight.api.entity.ImprovedProjectileEntity" {
import {$CompoundTag$$Type} from "net.minecraft.nbt.CompoundTag"
import {$Optional} from "java.util.Optional"
import {$Level} from "net.minecraft.world.level.Level"
import {$ThrowableItemProjectile} from "net.minecraft.world.entity.projectile.ThrowableItemProjectile"
import {$HolderLookup$Provider$$Type} from "net.minecraft.core.HolderLookup$Provider"
import {$MoverType$$Type} from "net.minecraft.world.entity.MoverType"
import {$Vec3$$Type} from "net.minecraft.world.phys.Vec3"
import {$ScoreHolder} from "net.minecraft.world.scores.ScoreHolder"
import {$Tag} from "net.minecraft.nbt.Tag"
import {$PortalProcessor} from "net.minecraft.world.entity.PortalProcessor"
import {$Entity$$Type} from "net.minecraft.world.entity.Entity"
import {$BlockPos} from "net.minecraft.core.BlockPos"
import {$GameProfile$$Type} from "com.mojang.authlib.GameProfile"

export class $ImprovedProjectileEntity extends $ThrowableItemProjectile {
 "invulnerableTime": integer
static readonly "UUID_TAG": StringJS
static readonly "BASE_TICKS_REQUIRED_TO_FREEZE": integer
 "fallDistance": float
 "hasImpulse": boolean
 "portalProcess": $PortalProcessor
 "verticalCollision": boolean
static readonly "DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5": double
static readonly "MAX_ENTITY_TAG_COUNT": integer
static readonly "DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2": float
 "verticalCollisionBelow": boolean
 "tickCount": integer
 "noPhysics": boolean
 "yo": double
 "yOld": double
 "leftOwner": boolean
static readonly "DEFAULT_BB_WIDTH": float
 "minorHorizontalCollision": boolean
static readonly "BOARDING_COOLDOWN": integer
static readonly "DEFAULT_BB_HEIGHT": float
 "yRotO": float
static readonly "CONTENTS_SLOT_INDEX": integer
 "level": $Level
 "walkDistO": float
 "moveDist": float
static readonly "FREEZE_HURT_FREQUENCY": integer
 "flyDist": float
 "isInPowderSnow": boolean
static readonly "ATTACHMENTS_NBT_KEY": StringJS
static readonly "ID_TAG": StringJS
 "hasBeenShot": boolean
 "mainSupportingBlockPos": $Optional<($BlockPos)>
static readonly "PASSENGERS_TAG": StringJS
static readonly "DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0": double
 "blocksBuilding": boolean
 "xRotO": float
 "wasOnFire": boolean
 "zo": double
 "zOld": double
static readonly "TOTAL_AIR_SUPPLY": integer
 "xo": double
 "walkDist": float
 "xOld": double
 "noCulling": boolean
 "wasInPowderSnow": boolean
static readonly "BASE_SAFE_FALL_DISTANCE": integer
 "hurtMarked": boolean
 "horizontalCollision": boolean

public "move"(arg0: $MoverType$$Type, arg1: $Vec3$$Type): void
public "tick"(): void
public "hasReachedEndOfLife"(): boolean
public "spawnTrailParticles"(): void
public "getDefaultShootVelocity"(): float
public "shoot"(arg0: double, arg1: double, arg2: double, arg3: float, arg4: float): void
public "setNoPhysics"(arg0: boolean): void
public "isNoPhysics"(): boolean
public "shootFromRotation"(arg0: $Entity$$Type, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float): void
public "reachedEndOfLife"(): void
public "canHarmOwner"(): boolean
public "hasLeftOwner"(): boolean
public "addAdditionalSaveData"(arg0: $CompoundTag$$Type): void
public "readAdditionalSaveData"(arg0: $CompoundTag$$Type): void
public static "fromGameProfile"(arg0: $GameProfile$$Type): $ScoreHolder
public static "forNameOnly"(arg0: StringJS): $ScoreHolder
/**
 * 
 * @deprecated
 */
public "serializeNBT"(arg0: $HolderLookup$Provider$$Type): $Tag
get "defaultShootVelocity"(): float
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ImprovedProjectileEntity$$Type = ($ImprovedProjectileEntity);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ImprovedProjectileEntity$$Original = $ImprovedProjectileEntity;}
declare module "net.mehvahdjukaar.moonlight.api.item.IFirstPersonAnimationProvider" {
import {$HumanoidArm, $HumanoidArm$$Type} from "net.minecraft.world.entity.HumanoidArm"
import {$Player, $Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$InteractionHand, $InteractionHand$$Type} from "net.minecraft.world.InteractionHand"
import {$PoseStack, $PoseStack$$Type} from "com.mojang.blaze3d.vertex.PoseStack"
import {$Item$$Type} from "net.minecraft.world.item.Item"

export interface $IFirstPersonAnimationProvider$$Interface {

(arg0: $Player, arg1: $ItemStack, arg2: $InteractionHand, arg3: $HumanoidArm, arg4: $PoseStack, arg5: float, arg6: float, arg7: float, arg8: float): void
}

export class $IFirstPersonAnimationProvider implements $IFirstPersonAnimationProvider$$Interface {
static "get"(arg0: $Item$$Type): $IFirstPersonAnimationProvider
 "animateItemFirstPerson"(arg0: $Player$$Type, arg1: $ItemStack$$Type, arg2: $InteractionHand$$Type, arg3: $HumanoidArm$$Type, arg4: $PoseStack$$Type, arg5: float, arg6: float, arg7: float, arg8: float): void
static "attachToItem"(arg0: $Item$$Type, arg1: $IFirstPersonAnimationProvider$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IFirstPersonAnimationProvider$$Type = ((arg0: $Player, arg1: $ItemStack, arg2: $InteractionHand, arg3: $HumanoidArm, arg4: $PoseStack, arg5: float, arg6: float, arg7: float, arg8: float) => void);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IFirstPersonAnimationProvider$$Original = $IFirstPersonAnimationProvider;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.ModFlowingFluid" {
import {$ReplacementMatch} from "dev.latvian.mods.kubejs.recipe.match.ReplacementMatch"
import {$Fluid, $Fluid$$Type} from "net.minecraft.world.level.material.Fluid"
import {$IdMapper} from "net.minecraft.core.IdMapper"
import {$FlowingFluid} from "net.minecraft.world.level.material.FlowingFluid"
import {$ModFluidRenderProperties} from "net.mehvahdjukaar.moonlight.api.client.ModFluidRenderProperties"
import {$IntegerProperty} from "net.minecraft.world.level.block.state.properties.IntegerProperty"
import {$BooleanProperty} from "net.minecraft.world.level.block.state.properties.BooleanProperty"
import {$ModFlowingFluid$Properties} from "net.mehvahdjukaar.moonlight.api.fluids.ModFlowingFluid$Properties"
import {$FluidState} from "net.minecraft.world.level.material.FluidState"
import {$FluidType} from "net.neoforged.neoforge.fluids.FluidType"

/**
 * 
 * @deprecated
 */
export class $ModFlowingFluid extends $FlowingFluid {
static readonly "FLUID_STATE_REGISTRY": $IdMapper<($FluidState)>
static readonly "FALLING": $BooleanProperty
static readonly "LEVEL": $IntegerProperty

public static "properties"(): $ModFlowingFluid$Properties
public "getSource"(): $Fluid
public "getFlowing"(): $Fluid
public "isSame"(arg0: $Fluid$$Type): boolean
public "createRenderProperties"(): $ModFluidRenderProperties
public "getFluidType"(): $FluidType
public static "checkSpecialEquality"(arg1: any, arg2: any, arg3: boolean): boolean
public static "wrap"(o: any): $ReplacementMatch
get "source"(): $Fluid
get "flowing"(): $Fluid
get "fluidType"(): $FluidType
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ModFlowingFluid$$Type = ($ModFlowingFluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ModFlowingFluid$$Original = $ModFlowingFluid;}
declare module "net.mehvahdjukaar.moonlight.api.block.IBlockHolder" {
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export interface $IBlockHolder$$Interface {
get "heldBlock"(): $BlockState
set "heldBlock"(value: $BlockState$$Type)
}

export class $IBlockHolder implements $IBlockHolder$$Interface {
 "getHeldBlock"(): $BlockState
 "getHeldBlock"(arg0: integer): $BlockState
 "setHeldBlock"(arg0: $BlockState$$Type, arg1: integer): boolean
 "setHeldBlock"(arg0: $BlockState$$Type): boolean
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IBlockHolder$$Type = ($IBlockHolder);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IBlockHolder$$Original = $IBlockHolder;}
declare module "net.mehvahdjukaar.moonlight.api.map.CustomMapData$DirtyDataPatch" {
import {$CustomMapData$Type, $CustomMapData$Type$$Type} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData$Type"
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Map$$Type} from "java.util.Map"
import {$CustomMapData, $CustomMapData$$Type} from "net.mehvahdjukaar.moonlight.api.map.CustomMapData"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$Record} from "java.lang.Record"

export class $CustomMapData$DirtyDataPatch<P, D extends $CustomMapData<(object), (object)>> extends $Record {
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($CustomMapData$DirtyDataPatch<(never), (never)>)>

constructor(type: $CustomMapData$Type$$Type<(P), (D)>, patch: P)

public "type"(): $CustomMapData$Type<(P), (D)>
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "apply"(arg0: $Map$$Type<($CustomMapData$Type$$Type<(never), (never)>), ($CustomMapData$$Type<(never), (never)>)>): void
public "patch"(): P
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomMapData$DirtyDataPatch$$Type<P, D> = ({"patch"?: P, "type"?: $CustomMapData$Type$$Type<(P), (D)>}) | ([patch?: P, type?: $CustomMapData$Type$$Type<(P), (D)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomMapData$DirtyDataPatch$$Original<P, D> = $CustomMapData$DirtyDataPatch<(P), (D)>;}
declare module "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapMarker" {
import {$RecordCodecBuilder$Instance$$Type} from "com.mojang.serialization.codecs.RecordCodecBuilder$Instance"
import {$Products$P7} from "com.mojang.datafixers.Products$P7"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RecordCodecBuilder$Mu} from "com.mojang.serialization.codecs.RecordCodecBuilder$Mu"
import {$MLMapDecorationType, $MLMapDecorationType$$Type} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$MapItemSavedData$$Type} from "net.minecraft.world.level.saveddata.maps.MapItemSavedData"
import {$MLMapDecoration} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration"

export class $MLMapMarker<D extends $MLMapDecoration> {
static readonly "HAS_SMALL_TEXTURE_FLAG": integer
static readonly "REFERENCE_CODEC": $Codec<($MLMapMarker<(never)>)>

constructor(arg0: $Holder$$Type<($MLMapDecorationType<(never), (never)>)>, arg1: $BlockPos$$Type, arg2: float, arg3: ($Component$$Type)?, arg4: (boolean)?, arg5: (boolean)?, arg6: boolean)

public "equals"(arg0: any): boolean
public "hashCode"(): integer
public "getType"(): $Holder<($MLMapDecorationType<(never), (never)>)>
public "getDisplayName"(): $Optional<($Component)>
public "getFlags"(): integer
public "shouldSave"(): boolean
public "preventsExtending"(): boolean
public static "baseCodecGroup"<T extends $MLMapMarker<(object)>>(arg0: $RecordCodecBuilder$Instance$$Type<(T)>): $Products$P7<($RecordCodecBuilder$Mu<(T)>), ($Holder<($MLMapDecorationType<(never), (never)>)>), ($BlockPos), (float), ($Optional<($Component)>), ($Optional<(boolean)>), ($Optional<(boolean)>), (boolean)>
public "getMarkerUniqueId"(): StringJS
public "shouldRefreshFromWorld"(): boolean
public "getRotation"(): float
public "getPos"(): $BlockPos
public "createDecorationFromMarker"(arg0: $MapItemSavedData$$Type): D
public "hasFlag"(arg0: integer): boolean
get "type"(): $Holder<($MLMapDecorationType<(never), (never)>)>
get "displayName"(): $Optional<($Component)>
get "flags"(): integer
get "markerUniqueId"(): StringJS
get "rotation"(): float
get "pos"(): $BlockPos
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MLMapMarker$$Type<D> = ($MLMapMarker<(D)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MLMapMarker$$Original<D> = $MLMapMarker<(D)>;}
declare module "net.mehvahdjukaar.moonlight.api.block.ModStairBlock" {
import {$StairsShape} from "net.minecraft.world.level.block.state.properties.StairsShape"
import {$StairBlock} from "net.minecraft.world.level.block.StairBlock"
import {$Block, $Block$$Type} from "net.minecraft.world.level.block.Block"
import {$Half} from "net.minecraft.world.level.block.state.properties.Half"
import {$BlockBehaviour$Properties$$Type} from "net.minecraft.world.level.block.state.BlockBehaviour$Properties"
import {$IdMapper} from "net.minecraft.core.IdMapper"
import {$Supplier$$Type} from "java.util.function.Supplier"
import {$BooleanProperty} from "net.minecraft.world.level.block.state.properties.BooleanProperty"
import {$Item} from "net.minecraft.world.item.Item"
import {$EnumProperty} from "net.minecraft.world.level.block.state.properties.EnumProperty"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$DirectionProperty} from "net.minecraft.world.level.block.state.properties.DirectionProperty"
import {$BlockState} from "net.minecraft.world.level.block.state.BlockState"

export class $ModStairBlock extends $StairBlock {
static readonly "UPDATE_IMMEDIATE": integer
 "item": $Item
static readonly "CODEC": $MapCodec<($ModStairBlock)>
static readonly "UPDATE_NEIGHBORS": integer
static readonly "INDESTRUCTIBLE": float
static readonly "UPDATE_NONE": integer
static readonly "UPDATE_INVISIBLE": integer
static readonly "UPDATE_MOVE_BY_PISTON": integer
static readonly "UPDATE_LIMIT": integer
static readonly "HALF": $EnumProperty<($Half)>
static readonly "SHAPE": $EnumProperty<($StairsShape)>
static readonly "BLOCK_STATE_REGISTRY": $IdMapper<($BlockState)>
static readonly "UPDATE_ALL": integer
static readonly "UPDATE_ALL_IMMEDIATE": integer
static readonly "WATERLOGGED": $BooleanProperty
static readonly "UPDATE_KNOWN_SHAPE": integer
static readonly "UPDATE_SUPPRESS_DROPS": integer
static readonly "INSTANT": float
static readonly "UPDATE_CLIENTS": integer
static readonly "FACING": $DirectionProperty

constructor(arg0: $Supplier$$Type<($Block$$Type)>, arg1: $BlockBehaviour$Properties$$Type)

public "getBaseBlock"(): $Block
public "codec"(): $MapCodec<($ModStairBlock)>
public static "checkSpecialEquality"(arg1: any, arg2: any, arg3: boolean): boolean
get "baseBlock"(): $Block
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ModStairBlock$$Type = ($ModStairBlock);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ModStairBlock$$Original = $ModStairBlock;}
declare module "net.mehvahdjukaar.moonlight.api.map.decoration.SimpleMapMarker" {
import {$Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$MLMapDecorationType$$Type} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType"
import {$MLMapMarker} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapMarker"
import {$Component$$Type} from "net.minecraft.network.chat.Component"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$Holder$$Type} from "net.minecraft.core.Holder"
import {$MLMapDecoration} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration"

export class $SimpleMapMarker extends $MLMapMarker<($MLMapDecoration)> {
static readonly "HAS_SMALL_TEXTURE_FLAG": integer
static readonly "DIRECT_CODEC": $MapCodec<($SimpleMapMarker)>
static readonly "REFERENCE_CODEC": $Codec<($MLMapMarker<(never)>)>

constructor(arg0: $Holder$$Type<($MLMapDecorationType<(never), (never)>)>, arg1: $BlockPos$$Type, arg2: float, arg3: ($Component$$Type)?)
constructor(arg0: $Holder$$Type<($MLMapDecorationType<(never), (never)>)>, arg1: $BlockPos$$Type, arg2: float, arg3: ($Component$$Type)?, arg4: (boolean)?, arg5: (boolean)?, arg6: boolean)

}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SimpleMapMarker$$Type = ($SimpleMapMarker);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SimpleMapMarker$$Original = $SimpleMapMarker;}
declare module "net.mehvahdjukaar.moonlight.api.misc.WorldSavedDataType$Scope" {
import {$Enum} from "java.lang.Enum"

export class $WorldSavedDataType$Scope extends $Enum<($WorldSavedDataType$Scope)> {
static readonly "SINGLE_OVERWORLD": $WorldSavedDataType$Scope
static readonly "PER_LEVEL": $WorldSavedDataType$Scope

public static "values"(): ($WorldSavedDataType$Scope)[]
public static "valueOf"(arg0: StringJS): $WorldSavedDataType$Scope
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WorldSavedDataType$Scope$$Type = (("single_overworld") | ("per_level"));
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WorldSavedDataType$Scope$$Original = $WorldSavedDataType$Scope;}
declare module "net.mehvahdjukaar.moonlight.api.events.SimpleEvent" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export interface $SimpleEvent$$Interface {
}

export class $SimpleEvent implements $SimpleEvent$$Interface {
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SimpleEvent$$Type = ($SimpleEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SimpleEvent$$Original = $SimpleEvent;}
declare module "net.mehvahdjukaar.moonlight.api.map.decoration.MLJsonMapDecorationType" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$MLMapDecorationType} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$RuleTest, $RuleTest$$Type} from "net.minecraft.world.level.levelgen.structure.templatesystem.RuleTest"
import {$Holder} from "net.minecraft.core.Holder"
import {$MLMapDecoration} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration"
import {$SimpleMapMarker} from "net.mehvahdjukaar.moonlight.api.map.decoration.SimpleMapMarker"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Structure, $Structure$$Type} from "net.minecraft.world.level.levelgen.structure.Structure"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$HolderSet, $HolderSet$$Type} from "net.minecraft.core.HolderSet"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LevelAccessor$$Type} from "net.minecraft.world.level.LevelAccessor"

export class $MLJsonMapDecorationType extends $MLMapDecorationType<($MLMapDecoration), ($SimpleMapMarker)> {
static readonly "CODEC": $Codec<($Holder<($MLMapDecorationType<(never), (never)>)>)>
static readonly "DIRECT_CODEC": $Codec<($MLMapDecorationType<(never), (never)>)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($Holder<($MLMapDecorationType<(never), (never)>)>)>

constructor(arg0: ($RuleTest$$Type)?, arg1: ($Component$$Type)?, arg2: float, arg3: integer, arg4: ($HolderSet$$Type<($Structure$$Type)>)?)
constructor(arg0: ($RuleTest$$Type)?, arg1: ($Component$$Type)?, arg2: float, arg3: integer)
constructor(arg0: ($RuleTest$$Type)?)

public "getTarget"(): $Optional<($RuleTest)>
public "getDisplayName"(): $Optional<($Component)>
public "getDefaultMapColor"(): integer
public "getCustomFactoryID"(): $ResourceLocation
public "isFromWorld"(): boolean
public "getAssociatedStructure"(): $Optional<($HolderSet<($Structure)>)>
public "createMarkerFromWorld"(arg0: $LevelAccessor$$Type, arg1: $BlockPos$$Type): $SimpleMapMarker
public "getRotation"(): float
get "target"(): $Optional<($RuleTest)>
get "displayName"(): $Optional<($Component)>
get "defaultMapColor"(): integer
get "customFactoryID"(): $ResourceLocation
get "fromWorld"(): boolean
get "associatedStructure"(): $Optional<($HolderSet<($Structure)>)>
get "rotation"(): float
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MLJsonMapDecorationType$$Type = ($MLJsonMapDecorationType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MLJsonMapDecorationType$$Original = $MLJsonMapDecorationType;}
declare module "net.mehvahdjukaar.moonlight.api.events.IFireConsumeBlockEvent" {
import {$Direction, $Direction$$Type} from "net.minecraft.core.Direction"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LevelAccessor} from "net.minecraft.world.level.LevelAccessor"
import {$SimpleEvent$$Interface} from "net.mehvahdjukaar.moonlight.api.events.SimpleEvent"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export interface $IFireConsumeBlockEvent$$Interface extends $SimpleEvent$$Interface {
get "state"(): $BlockState
get "level"(): $LevelAccessor
get "face"(): $Direction
get "chance"(): integer
get "age"(): integer
get "finalState"(): $BlockState
set "finalState"(value: $BlockState$$Type)
get "pos"(): $BlockPos
}

export class $IFireConsumeBlockEvent implements $IFireConsumeBlockEvent$$Interface {
 "getState"(): $BlockState
static "create"(arg0: $BlockPos$$Type, arg1: $Level$$Type, arg2: $BlockState$$Type, arg3: integer, arg4: integer, arg5: $Direction$$Type, arg6: boolean): $IFireConsumeBlockEvent
 "getLevel"(): $LevelAccessor
 "wasReplacedByFire"(): boolean
 "getFace"(): $Direction
 "getChance"(): integer
 "getAge"(): integer
 "getFinalState"(): $BlockState
 "setFinalState"(arg0: $BlockState$$Type): void
 "getPos"(): $BlockPos
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IFireConsumeBlockEvent$$Type = ($IFireConsumeBlockEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IFireConsumeBlockEvent$$Original = $IFireConsumeBlockEvent;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$TintMethod" {
import {$Keyable} from "com.mojang.serialization.Keyable"
import {$Enum, $Enum$$Type} from "java.lang.Enum"
import {$StringRepresentable$EnumCodec} from "net.minecraft.util.StringRepresentable$EnumCodec"
import {$Codec} from "com.mojang.serialization.Codec"
import {$Supplier$$Type} from "java.util.function.Supplier"
import {$Function, $Function$$Type} from "java.util.function.Function"
import {$StringRepresentable, $StringRepresentable$$Type, $StringRepresentable$$Interface} from "net.minecraft.util.StringRepresentable"

export class $SoftFluid$TintMethod extends $Enum<($SoftFluid$TintMethod)> implements $StringRepresentable$$Interface {
static readonly "FLOWING": $SoftFluid$TintMethod
static readonly "CODEC": $Codec<($SoftFluid$TintMethod)>
static readonly "STILL_AND_FLOWING": $SoftFluid$TintMethod
static readonly "NO_TINT": $SoftFluid$TintMethod

public static "values"(): ($SoftFluid$TintMethod)[]
public static "valueOf"(arg0: StringJS): $SoftFluid$TintMethod
public "appliesToStill"(): boolean
public "appliesToFlowing"(): boolean
public "getSerializedName"(): StringJS
public static "keys"(arg0: ($StringRepresentable$$Type)[]): $Keyable
public static "fromEnumWithMapping"<E extends $Enum<(object)>>(arg0: $Supplier$$Type<((E)[])>, arg1: $Function$$Type<(StringJS), (StringJS)>): $StringRepresentable$EnumCodec<(E)>
public "getRemappedEnumConstantName"(): StringJS
public static "fromEnum"<E extends $Enum<(object)>>(arg0: $Supplier$$Type<((E)[])>): $StringRepresentable$EnumCodec<(E)>
public static "fromValues"<T extends $StringRepresentable>(arg0: $Supplier$$Type<((T)[])>): $Codec<(T)>
public static "createNameLookup"<T extends $StringRepresentable>(arg0: (T)[], arg1: $Function$$Type<(StringJS), (StringJS)>): $Function<(StringJS), (T)>
get "serializedName"(): StringJS
get "remappedEnumConstantName"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoftFluid$TintMethod$$Type = (("no_tint") | ("flowing") | ("still_and_flowing"));
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoftFluid$TintMethod$$Original = $SoftFluid$TintMethod;}
declare module "net.mehvahdjukaar.moonlight.api.misc.WorldSavedDataType" {
import {$WorldSavedData, $WorldSavedData$$Type} from "net.mehvahdjukaar.moonlight.api.misc.WorldSavedData"
import {$StreamCodec, $StreamCodec$$Type} from "net.minecraft.network.codec.StreamCodec"
import {$ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Codec, $Codec$$Type} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf, $RegistryFriendlyByteBuf$$Type} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$WorldSavedDataType$Scope$$Type} from "net.mehvahdjukaar.moonlight.api.misc.WorldSavedDataType$Scope"
import {$Function$$Type} from "java.util.function.Function"
import {$Supplier$$Type} from "java.util.function.Supplier"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$ServerLevel$$Type} from "net.minecraft.server.level.ServerLevel"

export class $WorldSavedDataType<D extends $WorldSavedData> {
static readonly "CODEC": $Codec<($WorldSavedDataType<($WorldSavedData)>)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($WorldSavedDataType<($WorldSavedData)>)>

constructor(arg0: $ResourceLocation$$Type, arg1: $Function$$Type<($ServerLevel), (D)>, arg2: $Supplier$$Type<($Codec$$Type<(D)>)>, arg3: $Supplier$$Type<($StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (D)>)>)
constructor(arg0: $ResourceLocation$$Type, arg1: $Function$$Type<($ServerLevel), (D)>, arg2: $Supplier$$Type<($Codec$$Type<(D)>)>, arg3: $Supplier$$Type<($StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (D)>)>, arg4: $WorldSavedDataType$Scope$$Type)

public "getName"(): StringJS
public "getData"(arg0: $Level$$Type): D
public "getStreamCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (D)>
public "setData"(arg0: $Level$$Type, arg1: D): void
public "getCodec"(): $Codec<(D)>
public "isSyncable"(): boolean
get "name"(): StringJS
get "streamCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (D)>
get "codec"(): $Codec<(D)>
get "syncable"(): boolean
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.MoonlightWorldSavedDataType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.MoonlightWorldSavedDataTypeTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WorldSavedDataType$$Type<D> = (Special.MoonlightWorldSavedDataType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WorldSavedDataType$$Original<D> = $WorldSavedDataType<(D)>;}
declare module "net.mehvahdjukaar.moonlight.api.worldgen.ISpecialSpawnsStructure" {
import {$Structure, $Structure$$Type} from "net.minecraft.world.level.levelgen.structure.Structure"
import {$MobCategory, $MobCategory$$Type} from "net.minecraft.world.entity.MobCategory"
import {$LongSet, $LongSet$$Type} from "it.unimi.dsi.fastutil.longs.LongSet"
import {$WeightedRandomList, $WeightedRandomList$$Type} from "net.minecraft.util.random.WeightedRandomList"
import {$StructureManager, $StructureManager$$Type} from "net.minecraft.world.level.StructureManager"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$MobSpawnSettings$SpawnerData, $MobSpawnSettings$SpawnerData$$Type} from "net.minecraft.world.level.biome.MobSpawnSettings$SpawnerData"

export interface $ISpecialSpawnsStructure$$Interface {

(arg0: $StructureManager, arg1: $Structure, arg2: $BlockPos, arg3: $LongSet, arg4: $MobCategory): $WeightedRandomList$$Type<($MobSpawnSettings$SpawnerData$$Type)>
}

export class $ISpecialSpawnsStructure implements $ISpecialSpawnsStructure$$Interface {
 "ml$getSpecialSpawns"(arg0: $StructureManager$$Type, arg1: $Structure$$Type, arg2: $BlockPos$$Type, arg3: $LongSet$$Type, arg4: $MobCategory$$Type): $WeightedRandomList<($MobSpawnSettings$SpawnerData)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ISpecialSpawnsStructure$$Type = ((arg0: $StructureManager, arg1: $Structure, arg2: $BlockPos, arg3: $LongSet, arg4: $MobCategory) => $WeightedRandomList$$Type<($MobSpawnSettings$SpawnerData$$Type)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ISpecialSpawnsStructure$$Original = $ISpecialSpawnsStructure;}
declare module "net.mehvahdjukaar.moonlight.api.map.CustomMapData$DirtyCounter" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export interface $CustomMapData$DirtyCounter$$Interface {
get "dirty"(): boolean
}

export class $CustomMapData$DirtyCounter implements $CustomMapData$DirtyCounter$$Interface {
 "isDirty"(): boolean
 "clearDirty"(): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomMapData$DirtyCounter$$Type = ($CustomMapData$DirtyCounter);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomMapData$DirtyCounter$$Original = $CustomMapData$DirtyCounter;}
declare module "net.mehvahdjukaar.moonlight.api.item.additional_placements.BlockPlacerItem" {
import {$Map, $Map$$Type} from "java.util.Map"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$SoundType$$Type} from "net.minecraft.world.level.block.SoundType"
import {$Block, $Block$$Type} from "net.minecraft.world.level.block.Block"
import {$BlockItem} from "net.minecraft.world.item.BlockItem"
import {$FoodProperties, $FoodProperties$$Type} from "net.minecraft.world.food.FoodProperties"
import {$InteractionResult} from "net.minecraft.world.InteractionResult"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Item$Properties$$Type} from "net.minecraft.world.item.Item$Properties"
import {$Item, $Item$$Type} from "net.minecraft.world.item.Item"
import {$LivingEntity$$Type} from "net.minecraft.world.entity.LivingEntity"
import {$UseOnContext$$Type} from "net.minecraft.world.item.context.UseOnContext"
import {$AdditionalItemPlacement, $AdditionalItemPlacement$$Type} from "net.mehvahdjukaar.moonlight.api.item.additional_placements.AdditionalItemPlacement"
import {$BlockPlaceContext$$Type} from "net.minecraft.world.item.context.BlockPlaceContext"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $BlockPlacerItem extends $BlockItem {
static readonly "BASE_ATTACK_DAMAGE_ID": $ResourceLocation
static readonly "DEFAULT_MAX_STACK_SIZE": integer
static readonly "MAX_BAR_WIDTH": integer
static readonly "BASE_ATTACK_SPEED_ID": $ResourceLocation
static readonly "ABSOLUTE_MAX_STACK_SIZE": integer
static readonly "BY_BLOCK": $Map<($Block), ($Item)>

constructor(arg0: $Block$$Type, arg1: $Item$Properties$$Type)

public static "get"(): $BlockPlacerItem
public "getFoodProperties"(arg0: $ItemStack$$Type, arg1: $LivingEntity$$Type): $FoodProperties
public "getBlock"(): $Block
public "canPlace"(arg0: $BlockPlaceContext$$Type, arg1: $BlockState$$Type): boolean
public "mimicPlace"(arg0: $BlockPlaceContext$$Type, arg1: $Block$$Type, arg2: $SoundType$$Type): $InteractionResult
public "mimicUseOn"(arg0: $UseOnContext$$Type, arg1: $Block$$Type, arg2: $FoodProperties$$Type): $InteractionResult
public "mimicGetPlacementState"(arg0: $BlockPlaceContext$$Type, arg1: $Block$$Type): $BlockState
public "registerBlocks"(arg0: $Map$$Type<($Block$$Type), ($Item$$Type)>, arg1: $Item$$Type): void
public "getDescriptionId"(): StringJS
public "moonlight$getAdditionalBehavior"(): $AdditionalItemPlacement
public "moonlight$setAdditionalBehavior"(arg0: $AdditionalItemPlacement$$Type): void
public "moonlight$getClientAnimationExtension"(): any
public "moonlight$setClientAnimationExtension"(arg0: any): void
public static "checkSpecialEquality"(arg1: any, arg2: any, arg3: boolean): boolean
get "block"(): $Block
get "descriptionId"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BlockPlacerItem$$Type = ($BlockPlacerItem);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BlockPlacerItem$$Original = $BlockPlacerItem;}
declare module "net.mehvahdjukaar.moonlight.api.item.additional_placements.AdditionalItemPlacement" {
import {$InteractionResult} from "net.minecraft.world.InteractionResult"
import {$BlockPlacerItem} from "net.mehvahdjukaar.moonlight.api.item.additional_placements.BlockPlacerItem"
import {$Block, $Block$$Type} from "net.minecraft.world.level.block.Block"
import {$UseOnContext$$Type} from "net.minecraft.world.item.context.UseOnContext"
import {$BlockPlaceContext, $BlockPlaceContext$$Type} from "net.minecraft.world.item.context.BlockPlaceContext"
import {$FoodProperties$$Type} from "net.minecraft.world.food.FoodProperties"
import {$BlockState} from "net.minecraft.world.level.block.state.BlockState"

export class $AdditionalItemPlacement {
constructor(arg0: $Block$$Type)

public "overrideGetPlacementState"(arg0: $BlockPlaceContext$$Type): $BlockState
public "toString"(): StringJS
public "overrideUseOn"(arg0: $UseOnContext$$Type, arg1: $FoodProperties$$Type): $InteractionResult
public "overridePlace"(arg0: $BlockPlaceContext$$Type): $InteractionResult
public static "getBlockPlacer"(): $BlockPlacerItem
public "overrideUpdatePlacementContext"(arg0: $BlockPlaceContext$$Type): $BlockPlaceContext
public "getPlacedBlock"(): $Block
public static get "blockPlacer"(): $BlockPlacerItem
get "placedBlock"(): $Block
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AdditionalItemPlacement$$Type = ($AdditionalItemPlacement);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AdditionalItemPlacement$$Original = $AdditionalItemPlacement;}
declare module "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Optional} from "java.util.Optional"
import {$MLMapMarker} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapMarker"
import {$Holder} from "net.minecraft.core.Holder"
import {$MLMapDecoration} from "net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecoration"
import {$BlockGetter$$Type} from "net.minecraft.world.level.BlockGetter"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$Structure} from "net.minecraft.world.level.levelgen.structure.Structure"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$HolderSet} from "net.minecraft.core.HolderSet"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$LevelAccessor$$Type} from "net.minecraft.world.level.LevelAccessor"
import {$MapCodec} from "com.mojang.serialization.MapCodec"

export class $MLMapDecorationType<D extends $MLMapDecoration, M extends $MLMapMarker<(object)>> {
static readonly "CODEC": $Codec<($Holder<($MLMapDecorationType<(never), (never)>)>)>
static readonly "DIRECT_CODEC": $Codec<($MLMapDecorationType<(never), (never)>)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($Holder<($MLMapDecorationType<(never), (never)>)>)>

public "getDefaultMapColor"(): integer
public "getMarkerCodec"(): $MapCodec<(M)>
public "getCustomFactoryID"(): $ResourceLocation
public "getDecorationCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (D)>
public "getAssociatedStructure"(): $Optional<($HolderSet<($Structure)>)>
public "createMarkerFromWorld"(arg0: $LevelAccessor$$Type, arg1: $BlockPos$$Type): M
/**
 * 
 * @deprecated
 */
public "createMarkerFromWorld"(arg0: $BlockGetter$$Type, arg1: $BlockPos$$Type): M
get "defaultMapColor"(): integer
get "markerCodec"(): $MapCodec<(M)>
get "customFactoryID"(): $ResourceLocation
get "decorationCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (D)>
get "associatedStructure"(): $Optional<($HolderSet<($Structure)>)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.MoonlightMapMarker
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.MoonlightMapMarkerTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MLMapDecorationType$$Type<D, M> = (Special.MoonlightMapMarker);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MLMapDecorationType$$Original<D, M> = $MLMapDecorationType<(D), (M)>;}
declare module "net.mehvahdjukaar.moonlight.api.fluids.FluidContainerList$Category" {
import {$Optional} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$List} from "java.util.List"
import {$Item} from "net.minecraft.world.item.Item"
import {$SoundEvent} from "net.minecraft.sounds.SoundEvent"

export class $FluidContainerList$Category {
static readonly "CODEC": $Codec<($FluidContainerList$Category)>

public "getCapacity"(): integer
public "isEmpty"(): boolean
/**
 * 
 * @deprecated
 */
public "getAmount"(): integer
public "getFillSound"(): $SoundEvent
public "getFirstFilled"(): $Optional<($Item)>
public "getEmptySound"(): $SoundEvent
public "getEmptyContainer"(): $Item
public "getFilledItems"(): $List<($Item)>
get "capacity"(): integer
get "empty"(): boolean
get "amount"(): integer
get "fillSound"(): $SoundEvent
get "firstFilled"(): $Optional<($Item)>
get "emptySound"(): $SoundEvent
get "emptyContainer"(): $Item
get "filledItems"(): $List<($Item)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FluidContainerList$Category$$Type = ($FluidContainerList$Category);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FluidContainerList$Category$$Original = $FluidContainerList$Category;}
