declare module "tictim.paraglider.wind.WindSource$Condition" {
import {$Codec} from "com.mojang.serialization.Codec"
import {$Consumer, $Consumer$$Type} from "java.util.function.Consumer"

export interface $WindSource$Condition$$Interface {

(arg0: integer, arg1: $Consumer<(StringJS)>, arg2: $Consumer<(StringJS)>): void
}

export class $WindSource$Condition implements $WindSource$Condition$$Interface {
static readonly "CODEC": $Codec<($WindSource$Condition)>

 "check"(arg0: integer, arg1: $Consumer$$Type<(StringJS)>, arg2: $Consumer$$Type<(StringJS)>): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WindSource$Condition$$Type = ((arg0: integer, arg1: $Consumer<(StringJS)>, arg2: $Consumer<(StringJS)>) => void);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WindSource$Condition$$Original = $WindSource$Condition;}
declare module "tictim.paraglider.wind.WindSource" {
import {$WindSource$Condition, $WindSource$Condition$$Type} from "tictim.paraglider.wind.WindSource$Condition"
import {$Codec} from "com.mojang.serialization.Codec"
import {$List, $List$$Type} from "java.util.List"
import {$Consumer$$Type} from "java.util.function.Consumer"
import {$Record} from "java.lang.Record"

export class $WindSource extends $Record {
static readonly "CODEC": $Codec<($WindSource)>
static readonly "DEFAULT_HEIGHT": integer

constructor(conditions: $List$$Type<($WindSource$Condition$$Type)>, height: integer)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "check"(arg0: $Consumer$$Type<(StringJS)>, arg1: $Consumer$$Type<(StringJS)>): void
public "conditions"(): $List<($WindSource$Condition)>
public "height"(): integer
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.ParagliderWindSources
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.ParagliderWindSourcesTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WindSource$$Type = (Special.ParagliderWindSources) | ({"conditions"?: $List$$Type<($WindSource$Condition$$Type)>, "height"?: integer}) | ([conditions?: $List$$Type<($WindSource$Condition$$Type)>, height?: integer]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WindSource$$Original = $WindSource;}
