declare module "twilightforest.util.Restriction" {
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Optional} from "java.util.Optional"
import {$Structure, $Structure$$Type} from "net.minecraft.world.level.levelgen.structure.Structure"
import {$Codec} from "com.mojang.serialization.Codec"
import {$List, $List$$Type} from "java.util.List"
import {$ResourceKey, $ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Enforcement, $Enforcement$$Type} from "twilightforest.util.Enforcement"
import {$Entity$$Type} from "net.minecraft.world.entity.Entity"
import {$Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$Record} from "java.lang.Record"

export class $Restriction extends $Record {
static readonly "CODEC": $Codec<($Restriction)>

constructor(hintStructureKey: $ResourceKey$$Type<($Structure)>, enforcement: $ResourceKey$$Type<($Enforcement)>, multiplier: float, lockedBiomeToast: $ItemStack$$Type, advancements: $List$$Type<($ResourceLocation$$Type)>)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "multiplier"(): float
public "advancements"(): $List<($ResourceLocation)>
public "hintStructureKey"(): $ResourceKey<($Structure)>
public "enforcement"(): $ResourceKey<($Enforcement)>
public "lockedBiomeToast"(): $ItemStack
public static "getRestrictionForBiome"(arg0: $Biome$$Type, arg1: $Entity$$Type): $Optional<($Restriction)>
public static "isBiomeSafeFor"(arg0: $Biome$$Type, arg1: $Entity$$Type): boolean
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightRestrictions
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightRestrictionsTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Restriction$$Type = (Special.TwilightRestrictions) | ({"advancements"?: $List$$Type<($ResourceLocation$$Type)>, "enforcement"?: $ResourceKey$$Type<($Enforcement)>, "multiplier"?: float, "hintStructureKey"?: $ResourceKey$$Type<($Structure)>, "lockedBiomeToast"?: $ItemStack$$Type}) | ([advancements?: $List$$Type<($ResourceLocation$$Type)>, enforcement?: $ResourceKey$$Type<($Enforcement)>, multiplier?: float, hintStructureKey?: $ResourceKey$$Type<($Structure)>, lockedBiomeToast?: $ItemStack$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Restriction$$Original = $Restriction;}
declare module "twilightforest.util.RootPlacer" {
import {$BiConsumer, $BiConsumer$$Type} from "java.util.function.BiConsumer"
import {$BlockPos, $BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $RootPlacer {
constructor(arg0: $BiConsumer$$Type<($BlockPos), ($BlockState)>, arg1: integer)

public "getPlacer"(): $BiConsumer<($BlockPos), ($BlockState)>
public "getRootPenetrability"(): integer
get "placer"(): $BiConsumer<($BlockPos), ($BlockState)>
get "rootPenetrability"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $RootPlacer$$Type = ($RootPlacer);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $RootPlacer$$Original = $RootPlacer;}
declare module "twilightforest.util.Enforcement" {
import {$Player, $Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$ServerLevel, $ServerLevel$$Type} from "net.minecraft.server.level.ServerLevel"
import {$Restriction, $Restriction$$Type} from "twilightforest.util.Restriction"
import {$TriConsumer, $TriConsumer$$Type} from "org.apache.logging.log4j.util.TriConsumer"
import {$Record} from "java.lang.Record"

export class $Enforcement extends $Record {
constructor(consumer: $TriConsumer$$Type<($Player$$Type), ($ServerLevel$$Type), ($Restriction$$Type)>)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "consumer"(): $TriConsumer<($Player), ($ServerLevel), ($Restriction)>
public static "enforceBiomeProgression"(arg0: $Player$$Type, arg1: $ServerLevel$$Type): void
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightforestEnforcement
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightforestEnforcementTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Enforcement$$Type = (Special.TwilightforestEnforcement) | ({"consumer"?: $TriConsumer$$Type<($Player$$Type), ($ServerLevel$$Type), ($Restriction$$Type)>}) | ([consumer?: $TriConsumer$$Type<($Player$$Type), ($ServerLevel$$Type), ($Restriction$$Type)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Enforcement$$Original = $Enforcement;}
