declare module "twilightforest.entity.passive.TinyBirdVariant" {
import {$RandomSource$$Type} from "net.minecraft.util.RandomSource"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$HolderSet, $HolderSet$$Type} from "net.minecraft.core.HolderSet"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$RegistryAccess$$Type} from "net.minecraft.core.RegistryAccess"
import {$Record} from "java.lang.Record"

export class $TinyBirdVariant extends $Record {
static readonly "CODEC": $Codec<($Holder<($TinyBirdVariant)>)>
static readonly "DIRECT_CODEC": $Codec<($TinyBirdVariant)>

constructor(arg0: $ResourceLocation$$Type)
constructor(texture: $ResourceLocation$$Type, spawnBiomes: ($HolderSet$$Type<($Biome$$Type)>)?)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public static "getVariant"(arg0: $RegistryAccess$$Type, arg1: $Holder$$Type<($Biome)>, arg2: $RandomSource$$Type): $Holder<($TinyBirdVariant)>
public "texture"(): $ResourceLocation
public "spawnBiomes"(): $Optional<($HolderSet<($Biome)>)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightTinyBirdVariant
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightTinyBirdVariantTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TinyBirdVariant$$Type = (Special.TwilightTinyBirdVariant) | ({"spawnBiomes"?: ($HolderSet$$Type<($Biome$$Type)>)?, "texture"?: $ResourceLocation$$Type}) | ([spawnBiomes?: ($HolderSet$$Type<($Biome$$Type)>)?, texture?: $ResourceLocation$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TinyBirdVariant$$Original = $TinyBirdVariant;}
declare module "twilightforest.entity.passive.DwarfRabbitVariant" {
import {$RandomSource$$Type} from "net.minecraft.util.RandomSource"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$HolderSet, $HolderSet$$Type} from "net.minecraft.core.HolderSet"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$RegistryAccess$$Type} from "net.minecraft.core.RegistryAccess"
import {$Record} from "java.lang.Record"

export class $DwarfRabbitVariant extends $Record {
static readonly "CODEC": $Codec<($Holder<($DwarfRabbitVariant)>)>
static readonly "DIRECT_CODEC": $Codec<($DwarfRabbitVariant)>

constructor(arg0: $ResourceLocation$$Type)
constructor(texture: $ResourceLocation$$Type, spawnBiomes: ($HolderSet$$Type<($Biome$$Type)>)?)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public static "getVariant"(arg0: $RegistryAccess$$Type, arg1: $Holder$$Type<($Biome)>, arg2: $RandomSource$$Type): $Holder<($DwarfRabbitVariant)>
public static "getRandomCommonVariant"(arg0: $RegistryAccess$$Type, arg1: $RandomSource$$Type): $Holder<($DwarfRabbitVariant)>
public "texture"(): $ResourceLocation
public "spawnBiomes"(): $Optional<($HolderSet<($Biome)>)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightDwarfRabbitVariant
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightDwarfRabbitVariantTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DwarfRabbitVariant$$Type = (Special.TwilightDwarfRabbitVariant) | ({"spawnBiomes"?: ($HolderSet$$Type<($Biome$$Type)>)?, "texture"?: $ResourceLocation$$Type}) | ([spawnBiomes?: ($HolderSet$$Type<($Biome$$Type)>)?, texture?: $ResourceLocation$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DwarfRabbitVariant$$Original = $DwarfRabbitVariant;}
