declare module "twilightforest.world.components.layer.vanillalegacy.context.BigContext" {
import {$Context$$Interface} from "twilightforest.world.components.layer.vanillalegacy.context.Context"
import {$Area, $Area$$Type} from "twilightforest.world.components.layer.vanillalegacy.Area"

export interface $BigContext$$Interface<R extends $Area> extends $Context$$Interface {
get "seed"(): long
}

export class $BigContext<R extends $Area> implements $BigContext$$Interface {
 "createResult"(arg0: $Area$$Type): R
 "createResult"(arg0: $Area$$Type, arg1: R): R
 "createResult"(arg0: $Area$$Type, arg1: R, arg2: R): R
 "getSeed"(): long
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BigContext$$Type<R> = ($BigContext<(R)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BigContext$$Original<R> = $BigContext<(R)>;}
declare module "twilightforest.world.components.layer.vanillalegacy.BiomeLayerFactory" {
import {$LazyArea} from "twilightforest.world.components.layer.vanillalegacy.area.LazyArea"
import {$LazyAreaContext$$Type} from "twilightforest.world.components.layer.vanillalegacy.context.LazyAreaContext"
import {$BiomeLayerType} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerType"
import {$LongFunction$$Type} from "java.util.function.LongFunction"

export interface $BiomeLayerFactory$$Interface {
get "type"(): $BiomeLayerType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightBiomeLayerStack
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightBiomeLayerStackTag
}

export class $BiomeLayerFactory implements $BiomeLayerFactory$$Interface {
 "getType"(): $BiomeLayerType
 "build"(arg0: $LongFunction$$Type<($LazyAreaContext$$Type)>): $LazyArea
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BiomeLayerFactory$$Type = (Special.TwilightBiomeLayerStack);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BiomeLayerFactory$$Original = $BiomeLayerFactory;}
declare module "twilightforest.world.components.layer.vanillalegacy.ZoomLayer$Factory" {
import {$LazyArea} from "twilightforest.world.components.layer.vanillalegacy.area.LazyArea"
import {$LazyAreaContext$$Type} from "twilightforest.world.components.layer.vanillalegacy.context.LazyAreaContext"
import {$BiomeLayerType} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerType"
import {$LongFunction$$Type} from "java.util.function.LongFunction"
import {$BiomeLayerFactory, $BiomeLayerFactory$$Type, $BiomeLayerFactory$$Interface} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerFactory"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$Record} from "java.lang.Record"

export class $ZoomLayer$Factory extends $Record implements $BiomeLayerFactory$$Interface {
static readonly "CODEC": $MapCodec<($ZoomLayer$Factory)>

constructor(salt: long, fuzzy: boolean, parent: $Holder$$Type<($BiomeLayerFactory)>)

public "parent"(): $Holder<($BiomeLayerFactory)>
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "getType"(): $BiomeLayerType
public "build"(arg0: $LongFunction$$Type<($LazyAreaContext$$Type)>): $LazyArea
public "fuzzy"(): boolean
public "salt"(): long
get "type"(): $BiomeLayerType
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ZoomLayer$Factory$$Type = ({"parent"?: $Holder$$Type<($BiomeLayerFactory)>, "fuzzy"?: boolean, "salt"?: long}) | ([parent?: $Holder$$Type<($BiomeLayerFactory)>, fuzzy?: boolean, salt?: long]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ZoomLayer$Factory$$Original = $ZoomLayer$Factory;}
declare module "twilightforest.world.components.layer.BiomeDensitySource$DensityData" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export class $BiomeDensitySource$DensityData {
readonly "depth": double
readonly "scale": double

constructor(arg0: double, arg1: double)

}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BiomeDensitySource$DensityData$$Type = ($BiomeDensitySource$DensityData);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BiomeDensitySource$DensityData$$Original = $BiomeDensitySource$DensityData;}
declare module "twilightforest.world.components.layer.vanillalegacy.BiomeLayerType" {
import {$BiomeLayerFactory, $BiomeLayerFactory$$Type} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerFactory"
import {$MapCodec, $MapCodec$$Type} from "com.mojang.serialization.MapCodec"

export interface $BiomeLayerType$$Interface {

(): $MapCodec$$Type<($BiomeLayerFactory$$Type)>
get "codec"(): $MapCodec<($BiomeLayerFactory)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightBiomeLayerType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightBiomeLayerTypeTag
}

export class $BiomeLayerType implements $BiomeLayerType$$Interface {
 "getCodec"(): $MapCodec<($BiomeLayerFactory)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BiomeLayerType$$Type = (Special.TwilightBiomeLayerType) | (() => $MapCodec$$Type<($BiomeLayerFactory$$Type)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BiomeLayerType$$Original = $BiomeLayerType;}
declare module "twilightforest.world.components.layer.vanillalegacy.area.LazyArea" {
import {$LinkedBlockingQueue$$Type} from "java.util.concurrent.LinkedBlockingQueue"
import {$ConcurrentHashMap$$Type} from "java.util.concurrent.ConcurrentHashMap"
import {$ResourceKey, $ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$Area$$Type, $Area$$Interface} from "twilightforest.world.components.layer.vanillalegacy.Area"

export class $LazyArea implements $Area$$Interface {
constructor(arg0: $ConcurrentHashMap$$Type<(long), ($ResourceKey$$Type<($Biome$$Type)>)>, arg1: $LinkedBlockingQueue$$Type<(long)>, arg2: integer, arg3: $Area$$Type)

public "getBiome"(arg0: integer, arg1: integer): $ResourceKey<($Biome)>
public "getMaxCache"(): integer
get "maxCache"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $LazyArea$$Type = ($LazyArea);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $LazyArea$$Original = $LazyArea;}
declare module "twilightforest.world.components.layer.FilteredBiomeLayer$Factory" {
import {$LazyArea} from "twilightforest.world.components.layer.vanillalegacy.area.LazyArea"
import {$LazyAreaContext$$Type} from "twilightforest.world.components.layer.vanillalegacy.context.LazyAreaContext"
import {$BiomeLayerType} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerType"
import {$LongFunction$$Type} from "java.util.function.LongFunction"
import {$BiomeLayerFactory, $BiomeLayerFactory$$Type, $BiomeLayerFactory$$Interface} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerFactory"
import {$ResourceKey, $ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"

export class $FilteredBiomeLayer$Factory implements $BiomeLayerFactory$$Interface {
static readonly "CODEC": $MapCodec<($FilteredBiomeLayer$Factory)>

constructor(arg0: long, arg1: $ResourceKey$$Type<($Biome)>, arg2: $Holder$$Type<($BiomeLayerFactory)>, arg3: $Holder$$Type<($BiomeLayerFactory)>)

public "getType"(): $BiomeLayerType
public "build"(arg0: $LongFunction$$Type<($LazyAreaContext$$Type)>): $LazyArea
public "filterKeep"(): $ResourceKey<($Biome)>
public "salt"(): long
public "filteredLayer"(): $Holder<($BiomeLayerFactory)>
public "fallbackLayer"(): $Holder<($BiomeLayerFactory)>
get "type"(): $BiomeLayerType
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FilteredBiomeLayer$Factory$$Type = ($FilteredBiomeLayer$Factory);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FilteredBiomeLayer$Factory$$Original = $FilteredBiomeLayer$Factory;}
declare module "twilightforest.world.components.layer.vanillalegacy.Area" {
import {$ResourceKey, $ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"

export interface $Area$$Interface {

(arg0: integer, arg1: integer): $ResourceKey$$Type<($Biome$$Type)>
}

export class $Area implements $Area$$Interface {
 "getBiome"(arg0: integer, arg1: integer): $ResourceKey<($Biome)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Area$$Type = ((arg0: integer, arg1: integer) => $ResourceKey$$Type<($Biome$$Type)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Area$$Original = $Area;}
declare module "twilightforest.world.components.layer.BiomeDensitySource" {
import {$Map$$Type} from "java.util.Map"
import {$Optional} from "java.util.Optional"
import {$List$$Type} from "java.util.List"
import {$TerrainColumn, $TerrainColumn$$Type} from "twilightforest.world.components.chunkgenerators.TerrainColumn"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"
import {$DensityFunction$FunctionContext$$Type} from "net.minecraft.world.level.levelgen.DensityFunction$FunctionContext"
import {$Codec} from "com.mojang.serialization.Codec"
import {$BiomeDensitySource$DensityData} from "twilightforest.world.components.layer.BiomeDensitySource$DensityData"
import {$BiomeLayerFactory$$Type} from "twilightforest.world.components.layer.vanillalegacy.BiomeLayerFactory"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$Biome, $Biome$$Type} from "net.minecraft.world.level.biome.Biome"
import {$Stream} from "java.util.stream.Stream"

export class $BiomeDensitySource {
static readonly "CODEC": $Codec<($BiomeDensitySource)>

constructor(arg0: $List$$Type<($TerrainColumn$$Type)>, arg1: $Holder$$Type<($BiomeLayerFactory)>)
constructor(arg0: $Map$$Type<($ResourceKey$$Type<($Biome$$Type)>), ($TerrainColumn$$Type)>, arg1: $Holder$$Type<($BiomeLayerFactory)>)

public "getTerrainColumn"(arg0: $ResourceKey$$Type<($Biome)>): $Optional<($TerrainColumn)>
public "getTerrainColumn"(arg0: integer, arg1: integer): $Optional<($TerrainColumn)>
public "getBiomeColumnKey"(arg0: integer, arg1: integer): $Holder<($Biome)>
public "sampleTerrain"(arg0: integer, arg1: integer, arg2: $DensityFunction$FunctionContext$$Type): $BiomeDensitySource$DensityData
public "addDebugInfo"(arg0: $List$$Type<(StringJS)>, arg1: $BlockPos$$Type): void
public "getNoiseBiome"(arg0: integer, arg1: integer, arg2: integer): $Holder<($Biome)>
public "collectPossibleBiomes"(): $Stream<($Holder<($Biome)>)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightBiomeTerrainData
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightBiomeTerrainDataTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BiomeDensitySource$$Type = (Special.TwilightBiomeTerrainData);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BiomeDensitySource$$Original = $BiomeDensitySource;}
declare module "twilightforest.world.components.layer.vanillalegacy.context.LazyAreaContext" {
import {$BigContext$$Interface} from "twilightforest.world.components.layer.vanillalegacy.context.BigContext"
import {$LazyArea, $LazyArea$$Type} from "twilightforest.world.components.layer.vanillalegacy.area.LazyArea"
import {$Area, $Area$$Type} from "twilightforest.world.components.layer.vanillalegacy.Area"

export class $LazyAreaContext implements $BigContext$$Interface<($LazyArea)> {
constructor(arg0: integer, arg1: long)

public "getSeed"(): long
public "createResult"(arg0: $Area$$Type, arg1: $Area$$Type): $Area
public "createResult"(arg0: $Area$$Type, arg1: $Area$$Type, arg2: $Area$$Type): $Area
public "createResult"(arg0: $Area$$Type): $Area
public "createResult"(arg0: $Area$$Type, arg1: $LazyArea$$Type, arg2: $LazyArea$$Type): $LazyArea
public "createResult"(arg0: $Area$$Type, arg1: $LazyArea$$Type): $LazyArea
get "seed"(): long
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $LazyAreaContext$$Type = ($LazyAreaContext);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $LazyAreaContext$$Original = $LazyAreaContext;}
declare module "twilightforest.world.components.layer.vanillalegacy.context.Context" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export interface $Context$$Interface {

(): long
get "seed"(): long
}

export class $Context implements $Context$$Interface {
 "getSeed"(): long
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Context$$Type = (() => long);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Context$$Original = $Context;}
