declare module "twilightforest.util.woods.WoodPalette$WoodShapes" {
import {$Enum} from "java.lang.Enum"

export class $WoodPalette$WoodShapes extends $Enum<($WoodPalette$WoodShapes)> {
static readonly "BANISTER": $WoodPalette$WoodShapes
static readonly "BUTTON": $WoodPalette$WoodShapes
static readonly "BLOCK": $WoodPalette$WoodShapes
static readonly "STAIRS": $WoodPalette$WoodShapes
static readonly "GATE": $WoodPalette$WoodShapes
static readonly "FENCE": $WoodPalette$WoodShapes
static readonly "SLAB": $WoodPalette$WoodShapes
static readonly "PLATE": $WoodPalette$WoodShapes
static readonly "INVALID": $WoodPalette$WoodShapes

public static "values"(): ($WoodPalette$WoodShapes)[]
public static "valueOf"(arg0: StringJS): $WoodPalette$WoodShapes
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WoodPalette$WoodShapes$$Type = (("block") | ("stairs") | ("slab") | ("button") | ("fence") | ("gate") | ("plate") | ("banister") | ("invalid"));
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WoodPalette$WoodShapes$$Original = $WoodPalette$WoodShapes;}
declare module "twilightforest.util.woods.WoodPalette" {
import {$Codec} from "com.mojang.serialization.Codec"
import {$Block$$Type} from "net.minecraft.world.level.block.Block"
import {$StructureTemplate$StructureBlockInfo, $StructureTemplate$StructureBlockInfo$$Type} from "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo"
import {$WoodPalette$WoodShapes} from "twilightforest.util.woods.WoodPalette$WoodShapes"
import {$Holder$$Type} from "net.minecraft.core.Holder"
import {$BlockState, $BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export class $WoodPalette {
static readonly "CODEC": $Codec<($WoodPalette)>

constructor(arg0: $Holder$$Type<($Block)>, arg1: $Holder$$Type<($Block)>, arg2: $Holder$$Type<($Block)>, arg3: $Holder$$Type<($Block)>, arg4: $Holder$$Type<($Block)>, arg5: $Holder$$Type<($Block)>, arg6: $Holder$$Type<($Block)>, arg7: $Holder$$Type<($Block)>)
constructor(arg0: $Block$$Type, arg1: $Block$$Type, arg2: $Block$$Type, arg3: $Block$$Type, arg4: $Block$$Type, arg5: $Block$$Type, arg6: $Block$$Type, arg7: $Block$$Type)

public "contains"(arg0: $Block$$Type): boolean
public "modifyBlockWithType"(arg0: $WoodPalette$$Type, arg1: $BlockState$$Type): $BlockState
public "modifyBlockWithType"(arg0: $WoodPalette$$Type, arg1: $StructureTemplate$StructureBlockInfo$$Type): $StructureTemplate$StructureBlockInfo
public "getWoodShapeFromBlock"(arg0: $Block$$Type): $WoodPalette$WoodShapes
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightWoodPalettes
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightWoodPalettesTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WoodPalette$$Type = (Special.TwilightWoodPalettes);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $WoodPalette$$Original = $WoodPalette;}
