declare module "twilightforest.item.travellers_gear.modifiers.TravellersEntryModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ItemAttributeModifiers$Entry, $ItemAttributeModifiers$Entry$$Type} from "net.minecraft.world.item.component.ItemAttributeModifiers$Entry"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List, $List$$Type} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$InsertableTravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.InsertableTravellersModifier"
import {$DataComponentType, $DataComponentType$$Type} from "net.minecraft.core.component.DataComponentType"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$Supplier$$Type} from "java.util.function.Supplier"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"
import {$Record} from "java.lang.Record"
import {$Unit, $Unit$$Type} from "net.minecraft.util.Unit"

export class $TravellersEntryModifier extends $Record implements $InsertableTravellersModifier$$Interface {
static readonly "CODEC": $MapCodec<($TravellersEntryModifier)>

constructor(group: $EquipmentSlotGroup$$Type, modifiers: $List$$Type<($ItemAttributeModifiers$Entry$$Type)>, markerComponent: $DataComponentType$$Type<($Unit$$Type)>, description: $List$$Type<($Component$$Type)>, builtin: boolean)
constructor(arg0: $EquipmentSlotGroup$$Type, arg1: $List$$Type<($ItemAttributeModifiers$Entry$$Type)>, arg2: $Supplier$$Type<($DataComponentType$$Type<($Unit$$Type)>)>, arg3: boolean)
constructor(arg0: $EquipmentSlotGroup$$Type, arg1: $List$$Type<($ItemAttributeModifiers$Entry$$Type)>, arg2: $Supplier$$Type<($DataComponentType$$Type<($Unit$$Type)>)>, arg3: $List$$Type<($Component$$Type)>, arg4: boolean)

public "modifiers"(): $List<($ItemAttributeModifiers$Entry)>
public "group"(): $EquipmentSlotGroup
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "description"(): $List<($Component)>
public "removeModifier"(arg0: $ItemStack$$Type): void
public "isAbility"(): boolean
public "builtin"(): boolean
public "markerComponent"(): $DataComponentType<($Unit)>
public "codec"(): $MapCodec<($TravellersModifier)>
public "addModifier"(arg0: $ItemStack$$Type): boolean
public "hasModifier"(arg0: $ItemStack$$Type): boolean
public "getDescription"(): $List<($Component)>
public "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
public static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
public "getPrefix"(): StringJS
get "ability"(): boolean
get "prefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TravellersEntryModifier$$Type = ({"group"?: $EquipmentSlotGroup$$Type, "markerComponent"?: $DataComponentType$$Type<($Unit$$Type)>, "modifiers"?: $List$$Type<($ItemAttributeModifiers$Entry$$Type)>, "builtin"?: boolean, "description"?: $List$$Type<($Component$$Type)>}) | ([group?: $EquipmentSlotGroup$$Type, markerComponent?: $DataComponentType$$Type<($Unit$$Type)>, modifiers?: $List$$Type<($ItemAttributeModifiers$Entry$$Type)>, builtin?: boolean, description?: $List$$Type<($Component$$Type)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TravellersEntryModifier$$Original = $TravellersEntryModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.TravellersModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Codec} from "com.mojang.serialization.Codec"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Component} from "net.minecraft.network.chat.Component"
import {$MapCodec} from "com.mojang.serialization.MapCodec"

export interface $TravellersModifier$$Interface {
get "ability"(): boolean
get "description"(): $List<($Component)>
get "prefix"(): StringJS
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightTravellersModifiers
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightTravellersModifiersTag
}

export class $TravellersModifier implements $TravellersModifier$$Interface {
static readonly "CODEC": $Codec<($TravellersModifier)>

 "group"(): $EquipmentSlotGroup
 "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
 "isAbility"(): boolean
 "codec"(): $MapCodec<($TravellersModifier)>
static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
 "hasModifier"(arg0: $ItemStack$$Type): boolean
 "getDescription"(): $List<($Component)>
 "getPrefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TravellersModifier$$Type = (Special.TwilightTravellersModifiers);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TravellersModifier$$Original = $TravellersModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.TransferableTravellersModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List, $List$$Type} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$InsertableTravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.InsertableTravellersModifier"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Component} from "net.minecraft.network.chat.Component"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"

export interface $TransferableTravellersModifier$$Interface extends $InsertableTravellersModifier$$Interface {
get "ability"(): boolean
get "description"(): $List<($Component)>
get "prefix"(): StringJS
}

export class $TransferableTravellersModifier implements $TransferableTravellersModifier$$Interface {
 "transfer"(arg0: $ItemStack$$Type, arg1: $List$$Type<($Ingredient$$Type)>): boolean
 "removeModifier"(arg0: $ItemStack$$Type): void
 "addModifier"(arg0: $ItemStack$$Type): boolean
 "group"(): $EquipmentSlotGroup
 "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
 "isAbility"(): boolean
 "codec"(): $MapCodec<($TravellersModifier)>
static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
 "hasModifier"(arg0: $ItemStack$$Type): boolean
 "getDescription"(): $List<($Component)>
 "getPrefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TransferableTravellersModifier$$Type = ($TransferableTravellersModifier);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TransferableTravellersModifier$$Original = $TransferableTravellersModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.display.ItemDisplayType" {
import {$ItemDisplay, $ItemDisplay$$Type} from "twilightforest.client.overlay.display.ItemDisplay"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Predicate, $Predicate$$Type} from "java.util.function.Predicate"
import {$Supplier, $Supplier$$Type} from "java.util.function.Supplier"
import {$Record} from "java.lang.Record"

export class $ItemDisplayType extends $Record {
constructor(validItems: $Predicate$$Type<($ItemStack)>, display: $Supplier$$Type<($ItemDisplay$$Type)>, slotTexture: ($ResourceLocation$$Type)?)

public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "display"(): $Supplier<($ItemDisplay)>
public "slotTexture"(): $Optional<($ResourceLocation)>
public "validItems"(): $Predicate<($ItemStack)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.TwilightItemDisplayType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.TwilightItemDisplayTypeTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ItemDisplayType$$Type = (Special.TwilightItemDisplayType) | ({"validItems"?: $Predicate$$Type<($ItemStack$$Type)>, "slotTexture"?: ($ResourceLocation$$Type)?, "display"?: $Supplier$$Type<($ItemDisplay$$Type)>}) | ([validItems?: $Predicate$$Type<($ItemStack$$Type)>, slotTexture?: ($ResourceLocation$$Type)?, display?: $Supplier$$Type<($ItemDisplay$$Type)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ItemDisplayType$$Original = $ItemDisplayType;}
declare module "twilightforest.item.travellers_gear.modifiers.TravellersModifiable" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export interface $TravellersModifiable$$Interface {

(): integer
get "modifierSlots"(): integer
}

export class $TravellersModifiable implements $TravellersModifiable$$Interface {
 "getModifierSlots"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TravellersModifiable$$Type = (() => integer);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TravellersModifiable$$Original = $TravellersModifiable;}
declare module "twilightforest.item.travellers_gear.modifiers.InsertableTravellersModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Component} from "net.minecraft.network.chat.Component"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type, $TravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"

export interface $InsertableTravellersModifier$$Interface extends $TravellersModifier$$Interface {
get "ability"(): boolean
get "description"(): $List<($Component)>
get "prefix"(): StringJS
}

export class $InsertableTravellersModifier implements $InsertableTravellersModifier$$Interface {
 "removeModifier"(arg0: $ItemStack$$Type): void
 "addModifier"(arg0: $ItemStack$$Type): boolean
 "group"(): $EquipmentSlotGroup
 "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
 "isAbility"(): boolean
 "codec"(): $MapCodec<($TravellersModifier)>
static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
 "hasModifier"(arg0: $ItemStack$$Type): boolean
 "getDescription"(): $List<($Component)>
 "getPrefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $InsertableTravellersModifier$$Type = ($InsertableTravellersModifier);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $InsertableTravellersModifier$$Original = $InsertableTravellersModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.BuiltinTravellersComponentModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$Component} from "net.minecraft.network.chat.Component"
import {$DataComponentType, $DataComponentType$$Type} from "net.minecraft.core.component.DataComponentType"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type, $TravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"
import {$Record} from "java.lang.Record"

export class $BuiltinTravellersComponentModifier extends $Record implements $TravellersModifier$$Interface {
static readonly "CODEC": $MapCodec<($BuiltinTravellersComponentModifier)>

constructor(group: $EquipmentSlotGroup$$Type, component: $DataComponentType$$Type<(never)>)

public "group"(): $EquipmentSlotGroup
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "component"(): $DataComponentType<(never)>
public "isAbility"(): boolean
public "codec"(): $MapCodec<($TravellersModifier)>
public "hasModifier"(arg0: $ItemStack$$Type): boolean
public "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
public static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
public "getDescription"(): $List<($Component)>
public "getPrefix"(): StringJS
get "ability"(): boolean
get "description"(): $List<($Component)>
get "prefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BuiltinTravellersComponentModifier$$Type = ({"component"?: $DataComponentType$$Type<(never)>, "group"?: $EquipmentSlotGroup$$Type}) | ([component?: $DataComponentType$$Type<(never)>, group?: $EquipmentSlotGroup$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BuiltinTravellersComponentModifier$$Original = $BuiltinTravellersComponentModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.TransferableComponentModifier" {
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List, $List$$Type} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$DataComponentType, $DataComponentType$$Type} from "net.minecraft.core.component.DataComponentType"
import {$TransferableTravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.TransferableTravellersModifier"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$TypedDataComponent, $TypedDataComponent$$Type} from "net.minecraft.core.component.TypedDataComponent"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"
import {$Record} from "java.lang.Record"
import {$Unit, $Unit$$Type} from "net.minecraft.util.Unit"

export class $TransferableComponentModifier extends $Record implements $TransferableTravellersModifier$$Interface {
static readonly "CODEC": $MapCodec<($TransferableComponentModifier)>

constructor<T>(arg0: $EquipmentSlotGroup$$Type, arg1: $DataComponentType$$Type<($Unit$$Type)>, arg2: $DataComponentType$$Type<(T)>, arg3: T, arg4: $List$$Type<($Component$$Type)>)
constructor(group: $EquipmentSlotGroup$$Type, markerComponent: $DataComponentType$$Type<($Unit$$Type)>, transferableComponent: $TypedDataComponent$$Type<(never)>, description: $List$$Type<($Component$$Type)>)

public "group"(): $EquipmentSlotGroup
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "transfer"(arg0: $ItemStack$$Type, arg1: $List$$Type<($Ingredient$$Type)>): boolean
public "description"(): $List<($Component)>
public "removeModifier"(arg0: $ItemStack$$Type): void
public "isAbility"(): boolean
public "markerComponent"(): $DataComponentType<($Unit)>
public "codec"(): $MapCodec<($TravellersModifier)>
public "findDataComponentProviders"(arg0: $List$$Type<($Ingredient$$Type)>): $List<(($ItemStack)[])>
public "transferableComponent"(): $TypedDataComponent<(never)>
public "addModifier"(arg0: $ItemStack$$Type): boolean
public "hasModifier"(arg0: $ItemStack$$Type): boolean
public "getDescription"(): $List<($Component)>
public "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
public static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
public "getPrefix"(): StringJS
get "ability"(): boolean
get "prefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TransferableComponentModifier$$Type = ({"description"?: $List$$Type<($Component$$Type)>, "markerComponent"?: $DataComponentType$$Type<($Unit$$Type)>, "transferableComponent"?: $TypedDataComponent$$Type<(never)>, "group"?: $EquipmentSlotGroup$$Type}) | ([description?: $List$$Type<($Component$$Type)>, markerComponent?: $DataComponentType$$Type<($Unit$$Type)>, transferableComponent?: $TypedDataComponent$$Type<(never)>, group?: $EquipmentSlotGroup$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TransferableComponentModifier$$Original = $TransferableComponentModifier;}
declare module "twilightforest.item.travellers_gear.modifiers.TravellersComponentModifier" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$EquipmentSlotGroup, $EquipmentSlotGroup$$Type} from "net.minecraft.world.entity.EquipmentSlotGroup"
import {$List, $List$$Type} from "java.util.List"
import {$DataResult} from "com.mojang.serialization.DataResult"
import {$InsertableTravellersModifier$$Interface} from "twilightforest.item.travellers_gear.modifiers.InsertableTravellersModifier"
import {$DataComponentType$$Type} from "net.minecraft.core.component.DataComponentType"
import {$Component, $Component$$Type} from "net.minecraft.network.chat.Component"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$TypedDataComponent, $TypedDataComponent$$Type} from "net.minecraft.core.component.TypedDataComponent"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$TravellersModifier, $TravellersModifier$$Type} from "twilightforest.item.travellers_gear.modifiers.TravellersModifier"
import {$Record} from "java.lang.Record"

export class $TravellersComponentModifier extends $Record implements $InsertableTravellersModifier$$Interface {
static readonly "CODEC": $MapCodec<($TravellersComponentModifier)>

constructor<T>(arg0: $EquipmentSlotGroup$$Type, arg1: $DataComponentType$$Type<(T)>, arg2: T, arg3: $List$$Type<($Component$$Type)>)
constructor(group: $EquipmentSlotGroup$$Type, component: $TypedDataComponent$$Type<(never)>, description: $List$$Type<($Component$$Type)>)

public "group"(): $EquipmentSlotGroup
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "component"(): $TypedDataComponent<(never)>
public "description"(): $List<($Component)>
public "removeModifier"(arg0: $ItemStack$$Type): void
public "isAbility"(): boolean
public "codec"(): $MapCodec<($TravellersModifier)>
public "addModifier"(arg0: $ItemStack$$Type): boolean
public "hasModifier"(arg0: $ItemStack$$Type): boolean
public "getDescription"(): $List<($Component)>
public "isActive"(arg0: $ItemStack$$Type, arg1: $ResourceKey$$Type<($TravellersModifier)>, arg2: boolean): boolean
public static "validateEquipment"(arg0: $EquipmentSlotGroup$$Type): $DataResult<($EquipmentSlotGroup)>
public "getPrefix"(): StringJS
get "ability"(): boolean
get "prefix"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TravellersComponentModifier$$Type = ({"component"?: $TypedDataComponent$$Type<(never)>, "description"?: $List$$Type<($Component$$Type)>, "group"?: $EquipmentSlotGroup$$Type}) | ([component?: $TypedDataComponent$$Type<(never)>, description?: $List$$Type<($Component$$Type)>, group?: $EquipmentSlotGroup$$Type]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TravellersComponentModifier$$Original = $TravellersComponentModifier;}
