import {$StringUtilsWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.StringUtilsWrapper"
import {$AnimationHolder} from "io.redspace.ironsspellbooks.api.util.AnimationHolder"
import {$Stats} from "net.minecraft.stats.Stats"
import {$FluidAmounts} from "dev.latvian.mods.kubejs.util.FluidAmounts"
import {$Vector3f} from "org.joml.Vector3f"
import {$NBTWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.NBTWrapper"
import {$SizedIngredientWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.SizedIngredientWrapper"
import {$ItemWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.ItemWrapper"
import {$WispAttackGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.WispAttackGoal"
import {$WizardRecoverGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.WizardRecoverGoal"
import {$ImmutableCollections$MapN} from "java.util.ImmutableCollections$MapN"
import {$SpellBarrageGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.SpellBarrageGoal"
import {$BlockPredicate} from "net.minecraft.advancements.critereon.BlockPredicate"
import {$Vector4f} from "org.joml.Vector4f"
import {$MobEffectsPredicate} from "net.minecraft.advancements.critereon.MobEffectsPredicate"
import {$SpellData} from "io.redspace.ironsspellbooks.api.spells.SpellData"
import {$ICurioRenderer} from "top.theillusivec4.curios.api.client.ICurioRenderer"
import {$SpellRarity} from "io.redspace.ironsspellbooks.api.spells.SpellRarity"
import {$TextWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.TextWrapper"
import {$BlockStateProperties} from "net.minecraft.world.level.block.state.properties.BlockStateProperties"
import {$ModelResourceLocation} from "net.minecraft.client.resources.model.ModelResourceLocation"
import {$BlockWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.BlockWrapper"
import {$UUIDWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.UUIDWrapper"
import {$BlockStatePredicate} from "dev.latvian.mods.kubejs.block.state.BlockStatePredicate"
import {$Math} from "java.lang.Math"
import {$RegistryWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.RegistryWrapper"
import {$Player} from "net.minecraft.world.entity.player.Player"
import {$Potions} from "net.minecraft.world.item.alchemy.Potions"
import {$TextIcons} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.TextIcons"
import {$FluidPredicate} from "net.minecraft.advancements.critereon.FluidPredicate"
import {$BlockPos} from "net.minecraft.core.BlockPos"
import {$SpiritRepairRegexDataJSComponentWrapper} from "com.sammy.malum.compat.kubejs.wrapper.SpiritRepairRegexDataJSComponentWrapper"
import {$AbstractSpellWrapper} from "com.squoshi.irons_spells_js.spell.AbstractSpellWrapper"
import {$PotionRegistry} from "io.redspace.ironsspellbooks.registries.PotionRegistry"
import {$KJSTPluginUtils} from "dev.uncandango.kubejstweaks.kubejs.plugin.KJSTPluginUtils"
import {$Blocks} from "net.minecraft.world.level.block.Blocks"
import {$HashMap} from "java.util.HashMap"
import {$LightPredicate} from "net.minecraft.advancements.critereon.LightPredicate"
import {$NativeEventWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.NativeEventWrapper"
import {$GustDefenseGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.GustDefenseGoal"
import {$LootFunction} from "com.almostreliable.lootjs.loot.LootFunction"
import {$LootCondition} from "com.almostreliable.lootjs.loot.LootCondition"
import {$KMath} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.KMath"
import {$Predicates} from "com.almostreliable.lootjs.loot.Predicates"
import {$LootType} from "com.almostreliable.lootjs.core.LootType"
import {$MobEffectUtil} from "dev.latvian.mods.kubejs.util.MobEffectUtil"
import {$ParticleHelper} from "io.redspace.ironsspellbooks.util.ParticleHelper"
import {$ID} from "dev.latvian.mods.kubejs.util.ID"
import {$UtilsWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.UtilsWrapper"
import {$SpellRegistry} from "io.redspace.ironsspellbooks.api.registry.SpellRegistry"
import {$ItemFilter} from "com.almostreliable.lootjs.core.filters.ItemFilter"
import {$EntityEquipmentPredicate} from "net.minecraft.advancements.critereon.EntityEquipmentPredicate"
import {$Types} from "moe.wolfgirl.probejs.lang.typescript.code.type.Types"
import {$Vec3i} from "net.minecraft.core.Vec3i"
import {$IngredientWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.IngredientWrapper"
import {$DistancePredicate} from "net.minecraft.advancements.critereon.DistancePredicate"
import {$JsonUtils} from "dev.latvian.mods.kubejs.util.JsonUtils"
import {$Items} from "net.minecraft.world.item.Items"
import {$NumberProviderWrapper} from "com.almostreliable.lootjs.kube.wrappers.NumberProviderWrapper"
import {$CuriosApi} from "top.theillusivec4.curios.api.CuriosApi"
import {$SoundType} from "net.minecraft.world.level.block.SoundType"
import {$LocationPredicate} from "net.minecraft.advancements.critereon.LocationPredicate"
import {$CastType} from "io.redspace.ironsspellbooks.api.spells.CastType"
import {$WizardAttackGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.WizardAttackGoal"
import {$Duration} from "java.time.Duration"
import {$RotationAxis} from "dev.latvian.mods.kubejs.util.RotationAxis"
import {$JavaWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.JavaWrapper"
import {$SpiritJSComponentWrapper} from "com.sammy.malum.compat.kubejs.wrapper.SpiritJSComponentWrapper"
import {$CapabilityCurios$CuriosCapabilityBuilder} from "net.zhaiji.kubejscurios.curios.CapabilityCurios$CuriosCapabilityBuilder"
import {$DamageSource} from "net.minecraft.world.damagesource.DamageSource"
import {$EntityPredicate} from "net.minecraft.advancements.critereon.EntityPredicate"
import {$ConsoleJS} from "dev.latvian.mods.kubejs.script.ConsoleJS"
import {$FluidWrapper} from "dev.latvian.mods.kubejs.fluid.FluidWrapper"
import {$NbtPredicate} from "net.minecraft.advancements.critereon.NbtPredicate"
import {$WarlockAttackGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.WarlockAttackGoal"
import {$ColorWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.ColorWrapper"
import {$JsonIO} from "dev.latvian.mods.kubejs.util.JsonIO"
import {$ParticleOptionsWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.ParticleOptionsWrapper"
import {$MinMaxBounds$Doubles} from "net.minecraft.advancements.critereon.MinMaxBounds$Doubles"
import {$WizardSupportGoal} from "io.redspace.ironsspellbooks.entity.mobs.goals.WizardSupportGoal"
import {$DataMapWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.DataMapWrapper"
import {$AABBWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.AABBWrapper"
import {$Matrix4f} from "org.joml.Matrix4f"
import {$Vec3} from "net.minecraft.world.phys.Vec3"
import {$ItemTags} from "net.minecraft.tags.ItemTags"
import {$NBTIOWrapper} from "dev.latvian.mods.kubejs.util.NBTIOWrapper"
import {$DirectionWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.DirectionWrapper"
import {$EntitySelectorWrapper} from "dev.latvian.mods.kubejs.plugin.builtin.wrapper.EntitySelectorWrapper"
import {$Minecraft} from "net.minecraft.client.Minecraft"
import {$Long} from "java.lang.Long"
import {$Quaternionf} from "org.joml.Quaternionf"
import {$OverlayTexture} from "net.minecraft.client.renderer.texture.OverlayTexture"
import {$NotificationToastData} from "dev.latvian.mods.kubejs.util.NotificationToastData"
import {$EnchantmentPredicate} from "net.minecraft.advancements.critereon.EnchantmentPredicate"
import {$Utils} from "io.redspace.ironsspellbooks.api.util.Utils"
import {$TargetEntityCastData} from "io.redspace.ironsspellbooks.capabilities.magic.TargetEntityCastData"
import {$LootEntry} from "com.almostreliable.lootjs.core.entry.LootEntry"
import {$PlatformWrapper} from "dev.latvian.mods.kubejs.script.PlatformWrapper"
import {$Probe} from "moe.wolfgirl.probejs.plugin.Probe"
import {$ItemPredicate} from "net.minecraft.advancements.critereon.ItemPredicate"
import {$Matrix3f} from "org.joml.Matrix3f"
import {$SchoolRegistry} from "io.redspace.ironsspellbooks.api.registry.SchoolRegistry"

declare global {
const Facing: typeof $DirectionWrapper
const ParticleOptions: typeof $ParticleOptionsWrapper
const Platform: typeof $PlatformWrapper
const WizardSupportGoal: typeof $WizardSupportGoal
const RotationAxis: typeof $RotationAxis
const DataMap: typeof $DataMapWrapper
const Item: typeof $ItemWrapper
const WizardRecoverGoal: typeof $WizardRecoverGoal
const CuriosRenderer: typeof $ICurioRenderer
const OverlayTexture: typeof $OverlayTexture
const ID: typeof $ID
const ProbeJS: $Probe
const NativeEvents: typeof $NativeEventWrapper
const IronsSpellsParticleHelper: typeof $ParticleHelper
const MobEffectUtil: typeof $MobEffectUtil
const NBT: typeof $NBTWrapper
const KJSTweaks: typeof $KJSTPluginUtils
const LootFunction: $LootFunction
const NBTIO: typeof $NBTIOWrapper
const Matrix4f: typeof $Matrix4f
const SpellRarity: typeof $SpellRarity
const LootEntry: typeof $LootEntry
const SpellData: typeof $SpellData
const LightPredicate: typeof $LightPredicate
const CuriosApi: typeof $CuriosApi
const JavaMath: typeof $Math
const TargetEntityCastData: typeof $TargetEntityCastData
const GustDefenseGoal: typeof $GustDefenseGoal
const global: $HashMap
const ModelResourceLocation: typeof $ModelResourceLocation
const LootCondition: $LootCondition
const Direction: typeof $DirectionWrapper
const Notification: typeof $NotificationToastData
const Matrix3f: typeof $Matrix3f
const WizardAttackGoal: typeof $WizardAttackGoal
const BlockProperties: typeof $BlockStateProperties
const EntityEquipmentPredicate: typeof $EntityEquipmentPredicate
const Java: typeof $JavaWrapper
const Blocks: typeof $Blocks
const Quaternionf: typeof $Quaternionf
const Text: typeof $TextWrapper
const MobEffectsPredicate: typeof $MobEffectsPredicate
const NumberProvider: typeof $NumberProviderWrapper
const WispAttackGoal: typeof $WispAttackGoal
const Utils: typeof $UtilsWrapper
const Ingredient: typeof $IngredientWrapper
const BlockStatePredicate: typeof $BlockStatePredicate
const NbtPredicate: typeof $NbtPredicate
const BlockPredicate: typeof $BlockPredicate
const AABB: typeof $AABBWrapper
const FluidAmounts: typeof $FluidAmounts
const Types: typeof $Types
const GLFWInput: $ImmutableCollections$MapN
const LootType: typeof $LootType
const WarlockAttackGoal: typeof $WarlockAttackGoal
const TextIcons: typeof $TextIcons
const Items: typeof $Items
const MINUTE: $Long
const BlockPos: typeof $BlockPos
const SpellRegistry: typeof $SpellRegistry
const UUID: typeof $UUIDWrapper
const Client: $Minecraft
const FluidPredicate: typeof $FluidPredicate
const SoundType: typeof $SoundType
const Player: typeof $Player
const DistancePredicate: typeof $DistancePredicate
const CuriosJSCapabilityBuilder: $CapabilityCurios$CuriosCapabilityBuilder
const Fluid: typeof $FluidWrapper
const Color: typeof $ColorWrapper
const SchoolRegistry: typeof $SchoolRegistry
const ISSUtils: typeof $Utils
const Duration: typeof $Duration
const Range: typeof $MinMaxBounds$Doubles
const ISSAnimationHolder: typeof $AnimationHolder
const ItemPredicate: typeof $ItemPredicate
const EnchantmentPredicate: typeof $EnchantmentPredicate
const ItemFilter: typeof $ItemFilter
const KMath: typeof $KMath
const Stats: typeof $Stats
const Block: typeof $BlockWrapper
const Predicates: typeof $Predicates
const RepairRegex: typeof $SpiritRepairRegexDataJSComponentWrapper
const HOUR: $Long
const CastType: typeof $CastType
const Vec4f: typeof $Vector4f
const Spell: typeof $AbstractSpellWrapper
const Potions: typeof $Potions
const JsonUtils: typeof $JsonUtils
const StringUtils: typeof $StringUtilsWrapper
const SpellBarrageGoal: typeof $SpellBarrageGoal
const Component: typeof $TextWrapper
const console: $ConsoleJS
const JsonIO: typeof $JsonIO
const Vec3i: typeof $Vec3i
const EntitySelector: typeof $EntitySelectorWrapper
const DamageSource: typeof $DamageSource
const ItemTags: typeof $ItemTags
const SizedIngredient: typeof $SizedIngredientWrapper
const EntityPredicate: typeof $EntityPredicate
const Registry: typeof $RegistryWrapper
const Vec3f: typeof $Vector3f
const Vec3d: typeof $Vec3
const SpiritComponent: typeof $SpiritJSComponentWrapper
const ISSPotionRegistry: typeof $PotionRegistry
const SECOND: $Long
const LocationPredicate: typeof $LocationPredicate
}